### ISSUE TITLE
Add block work score computation

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1018]
Blocked by https://github.com/iotaledger/iota-sdk/issues/1015
Add block work score computation with the workScoreStructure from the ProtocolParameters

**Comment by Thoralf-M** [comment]
Related to this in iota-core https://github.com/iotaledger/iota-core/issues/285#issuecomment-1681828134

**Comment by Thoralf-M** [comment]
Work score calculation is defined here
https://github.com/iotaledger/tips-draft/pull/19/files/d59cd41be79d2d845f7ccce237b4749fc0c1b7d6..a7404961b28c7cac5b0aa7ee016db3b1a793967b
https://github.com/iotaledger/tips-draft/pull/20/files/9a2a3e6bbb669d3b005b16ff8005e9729574c344..3bcd377d2a49bd20fe8c7987e35ede803c215694

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1235
