### ISSUE TITLE
Replace sendMethods by prepareMethods, so sending and preparing is decoupled.

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/iota-sdk#104]
## Description

Based on https://github.com/iotaledger/wallet.rs/issues/1820, it becomes clear that there are some use cases where an unsigned output is required without actually sending it. Therefor, we should think about changing the API so that sending an output and building one are very easy to do separately.

## Motivation

This use case is important when we want to store unsigned transactions (e.g.: ledger flows). Potentially, this might also be interesting to create a batch of transactions and then send them all at once.

## Requirements

Write a list of what you want this feature to do.

1. all the send methods that return a `Promise<Transaction>` are refactored into `prepare...` methods that return a prepared output of type `OutputTypes`. This way ... 
2. the send methods can be removed from the message interface and ...
3. all transactions will use `sendOutput([ output[)`

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
> 2. This way the prepare methods can be removed from the message interface

Actually the prepare method would be there and replace the method that directly send the outputs in a transaction, no?

**Comment by Tuditi** [comment]
Depends on the design. I would remove the prepare methods and create a more generic "transaction builder" method, with two methods. `build()` or `prepare()` & `send()`. 

The only downside is that this might complicate things for us, since Electron's context bridge sanitizes return values that are complex objects.

Alternatively, it's possible to just add a `send()` method to `IOutput` that takes care of sending the transaction.

**Comment by Thoralf-M** [comment]
What's different to building a class on the JS side which internally first calls `prepareOutput()` and then `sendOutputs()`?

**Comment by Tuditi** [comment]
Nothing prevents us from doing that. But you already have that code inside the sdk and as a library you want to avoid code duplication across the different ecosystem projects by providing useful methods to your consumers.
