### ISSUE TITLE
change property names from camelCase to snake_case

### ISSUE THREAD

**Issue by qrayven** [iotaledger/iota-sdk#1042]
## Description

properties of many classes (i.e Unlock Conditions) are defined in camelCase. Go over the source code and replace them with the snake_case version

## Motivation

python style consistency

## Requirements

- change the source code of bindings
- fix examples

## Open questions (optional)

n/a

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1078
