### ISSUE TITLE
Wallet refactor

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#105]
- [x] Check if is_alias_transition() from iota.rs would be better to use instead of alias_state_transition() https://github.com/iotaledger/iota-sdk/pull/419
- [x] [Have a client in the AccountManager ?] https://github.com/iotaledger/iota-sdk/issues/423
- [x] Instead of `burn_native_token(), burn_nft(), destroy_alias(), destroy_foundry()` we could maybe just have a single `burn(burn: Burn)` method (burn is also optional in TransactionOptions, should maybe get removed there?) https://github.com/iotaledger/iota-sdk/issues/336

**Comment by DaughterOfMars** [comment]
- [x] I think `StorageManager` can be improved
