### ISSUE TITLE
[Bug]: (CLI) `restore` command asks for the cached stronghold instead of specified 

### ISSUE THREAD

**Issue by marc2332** [iotaledger/iota-sdk#1068]
### Issue description

I was trying to restore a wallet from a stronghold file and every time it asked my password and I wrote it told me the password was wrong...
Turns out, there was already a wallet in the same folder I was executing wallet restore ... so, I wasn't really writing the password for the stronghold I was trying to restore but for the wallet that was already in the folder. I found this behavior a bit confusing, so maybe it could be changed and instead prioritize the stronghold file that is being passed to the restore command and make it overwrite the wallet that is already in the folder, or, simply show a warning with something like "There seems to be a wallet in this folder already. First remove it to restore a new wallet."

### Version

https://github.com/iotaledger/iota-sdk/tree/ec1f64c98b71a13afe87c048d85f157d639909dd/cli

### Expected behaviour

Prioritize the stronghold file that is being passed to the restore command and make it overwrite the wallet that is already in the folder, or, simply show a warning with something like "There seems to be a wallet in this folder already. First remove it to restore a new wallet."

### Actual behaviour

It's prioritizing the cached stronghold

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. `mkdir tmp && cd tmp`
2. Create/restore a wallet (`Wallet A`)
3. Restore another wallet (`Wallet B`)

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1187
