### ISSUE TITLE
Add best practices to exchange integration guide

### ISSUE THREAD

**Issue by lzpap** [iotaledger/iota-sdk#107]
## Description

Enrich the [exchange integration guide](https://wiki.iota.org/wallet.rs/develop/libraries/nodejs/exchange_guide) with practical information and best practices:
 - [ ] Summary of what changed compared to the chrysalis version: api?
 - [x] How to access Shimmer rewards with wallet.rs?
 - [x] Warning and explanation about unlock conditions
 - [ ] Explanation of storage deposit system
 - [ ] General FAQ

**Comment by Thoralf-M** [comment]
> General FAQ

Any idea what to add there?
