### ISSUE TITLE
[Bug]: prepareCreateAliasOutput

### ISSUE THREAD

**Issue by drtwodog** [iotaledger/iota-sdk#1079]
### Issue description

I tried to create an application (for me) to test the wallet functions:

I am able to create a wallet and an account on it (gets an address). But when i try to create an alias (as described within the create.ts in the examples) it throws an error when i call the function:

    const transaction = await account
            .prepareCreateAliasOutput()
            .then((prepared) => prepared.send()); 

The old functions are deprecated. Therefore my question is how to create an address alias.

I use only 1 account / wallet (within the functions it is described, that it uses the first address if no parameters are given in prepareCreateAliasOutput() than it uses the first address (-> there is only 1 available).

Maby it is not a bug, but could you desribe how to create an address-alias?

### Version

I installed iota/sdk@1.0.5

### Expected behaviour

Address alias is created

### Actual behaviour

Error is thrown wenn i call      
const transaction = await account
            .prepareCreateAliasOutput()
            .then((prepared) => prepared.send()); 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

function -> where I set a specific alias: (_aliasId)

const walletOptions: WalletOptions = {
            storagePath: WalletDBPath,    //-> path only for the _aliasId
            clientOptions: {
                nodes: [process.env.NODE_URL],
            },
            coinType: CoinType.Shimmer,
            secretManager: {
                stronghold: {
                    snapshotPath: SNAPSHOT_PATH, //-> path only for the _aliasId
                    password: process.env.STRONGHOLD_PASSWORD,
                },
            },
        };

        const wallet = new Wallet(walletOptions);
       
        const MNEMONIC = await Utils.generateMnemonic();
        await wallet.storeMnemonic(MNEMONIC);

        // Create a new account
        const account = await wallet.createAccount({
            alias: _alias,
        });
        await wallet.setStrongholdPassword(process.env.STRONGHOLD_PASSWORD);

       
        const result = await account.sync();
           

        const transaction = await account
            .prepareCreateAliasOutput()
            .then((prepared) => prepared.send()); 

### Errors

Error: Sending the create-alias transaction...
undefined:1
undefined
^

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at exports.accountAdd (/app/indent_js/routes/account.js:96:39)

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by drtwodog** [comment]
I think the issue comes because i wanted to create an alias, because at the initial creation of the account with a new mnemonic the alias was not created.

**Comment by Thoralf-M** [comment]
```TS
const transaction = await account
        .prepareCreateAliasOutput()
        .then((prepared) => prepared.send()); 
```
works fine for me
The `Steps to reproduce the issue` are not really clear to me, can you share the full example? And are the env variables defined? For example `process.env.STRONGHOLD_PASSWORD`

**Comment by drtwodog** [comment]
ENV settings
```
WALLET_DB_PATH="./StrongholdFiles/DB/"
# The Stronghold snapshot file location used to store secrets
#STRONGHOLD_SNAPSHOT_PATH="./StrongholdFiles/Wallets/nident.stronghold"
STRONGHOLD_SNAPSHOT_PATH="./StrongholdFiles/Wallets/nident"

# The password to unlock the Stronghold snapshot file (Don't use it to protect real secrets!)

STRONGHOLD_PASSWORD="xxxxx"    
# everytime the same PW for tests
# The node URL to issue transactions with
NODE_URL="https://api.testnet.shimmer.network"
# The faucet URL to request test coins from
FAUCET_URL="https://faucet.testnet.shimmer.network/api/enqueue"
# The explorer URL to look up transactions, blocks, addresses and more
BECH32HRP="rms"
# rms or smr in real network
EXPLORER_URL="https://explorer.shimmer.network/testnet"
```

**Comment by drtwodog** [comment]
export async function createAccount(_alias) {
    
    console.log("createIotaAccount - createAccount");
    if (!process.env.FAUCET_URL) {
        throw new Error('.env FAUCET_URL is undefined');
    }
    if (!process.env.WALLET_DB_PATH) {
        throw new Error('.env WALLET_DB_PATH is undefined');
    }
    if (!process.env.STRONGHOLD_PASSWORD) {
        throw new Error(
            '.env STRONGHOLD_PASSWORD is undefined',
        );
    }
    if (!process.env.MNEMONIC) {
        throw new Error('.env MNEMONIC is undefined, see .env.example');
    }
    if (!process.env.NODE_URL) {
        throw new Error('.env NODE_URL is undefined, see .env.example');
    }
    var wallet;
    console.log("createIotaAccount1 - createAccount");
    
    try {
        var WalletDBPath= process.env.WALLET_DB_PATH+_alias+"/";
        var SNAPSHOT_PATH= process.env.STRONGHOLD_SNAPSHOT_PATH+_alias+".stronghold";

        const walletOptions: WalletOptions = {
            storagePath: WalletDBPath,
            clientOptions: {
                nodes: [process.env.NODE_URL],
            },
            coinType: CoinType.Shimmer,
            secretManager: {
                stronghold: {
                    snapshotPath: SNAPSHOT_PATH,
                    password: process.env.STRONGHOLD_PASSWORD,
                },
            },
        };

        const wallet = new Wallet(walletOptions);

  
        const MNEMONIC = await Utils.generateMnemonic();
        await wallet.storeMnemonic(MNEMONIC);
        
        
        // Create a new account
        //const secretManager: SecretManager = wallet.getSecretManager();
        
        const account = await wallet.createAccount({
            alias: _alias,
            bech32Hrp: process.env.BECH32HRP
                  });

        

        
        var result = await account.sync();

            // To create an address we need to unlock stronghold.
        await wallet.setStrongholdPassword(process.env.STRONGHOLD_PASSWORD);
        
       
        console.log("accounts", JSON.stringify(await wallet.getAccounts(),null,2));
        
       
        console.log('Generated new address', accountAddress);
        //var transaction = await account.prepareCreateAliasOutput();
        
        
        let balance = await account.sync();
        console.log(
            `Aliases BEFORE (${balance.aliases.length}):\n`,
            balance.aliases,
        );
        await wallet.setStrongholdPassword(process.env.STRONGHOLD_PASSWORD);
        const transaction = await account
            .prepareCreateAliasOutput()
            .then((prepared) => prepared.send());
         
                    // Wait for transaction to get included
        const blockId = await account.retryTransactionUntilIncluded(
            transaction.transactionId,
        );
        console.log(
            `Transaction included: ${process.env.EXPLORER_URL}/block/${blockId}`,
        );

        balance = await account.sync();
        console.log(
            `Aliases AFTER (${balance.aliases.length}):\n`,
            balance.aliases,
        );


        wallet.destroy();
        return {"accountAddress" :walletAddressBech32, "MNEMONIC" : MNEMONIC};
    } catch (error) {
        wallet.destroy();
        console.log('Error: ', error);
        
    }

}

**Comment by drtwodog** [comment]
HEy, see above the env and the coding - (super simple --!!)

But first of all. Thank you for that fast response!  Wow! Thanks!!

I hope you will find the issue!!

Remarks: 
I use several stronghold files (for each user) ..
For each stronghold I use for now the same PW but a different MNEMONIC for the account
I use node.js 20.5.0

**Comment by Thoralf-M** [comment]
I had to comment `console.log('Generated new address', accountAddress);` because it was undefined, then it got until the prepareAliasOutput() part and there returned `Error:  { type: 'wallet', error: '`no available inputs provided`' }` which is expected, because you first need funds before you can send a transaction

**Comment by drtwodog** [comment]
omg -> that is a typical "the error sits in front of the screen" :-)

Again thank you so much for your help and sorry to waste your time!!!

**Comment by drtwodog** [comment]
the issue opener was the error ... sorry!
