### ISSUE TITLE
Improve perfomance of @iota/sdk

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/iota-sdk#1097]
## Description

The performance of our app degrades a lot when switching over from @iota/wallet to @iota/sdk.

We measured the blocking time, which is a metric that makes the UI non-responsive due to processes running in the main process. On figure 1. you can see the performance profiling for @iota/wallet (blocking time 935 ms). On figure 2. you can see the performance profileing of @iota/sdk (blocking time 4583 ms). 

Additionally, we measured the time it takes to perform the API calls during login (I'll add some time measurements below):

The following functions take consistently longer:

    getNodeInfo()
    getAccounts()

The following functions take a long time generally:

    registerProposals
    getParticipationEventStatus
    
Time Measurements:
[Uploading performance-measure-sdk.md…]()

You can see that on the top, there is a full yellow bar for figure 2, which reflects that the main process is fully blocked. On figure one, the resources are much more balanced out. 

Figure 1 - Profiling of the login process with @iota/wallet 

![image](https://github.com/iotaledger/iota-sdk/assets/45079109/4cb08fa5-8596-4d5a-b5fe-28c038dd66dc)

Figure 2 - Profiling of the login process with @iota/sdk

![image](https://github.com/iotaledger/iota-sdk/assets/45079109/2f20db43-035d-4fd1-93ac-7294f6a3f5ec)

After doing some more profiling, we discovered that `listen_wallet` might be the culprit:

Figure 3 - Profiling indicates that listen_wallet blocks the main process
![image](https://github.com/iotaledger/iota-sdk/assets/45079109/0da5cdd1-f242-4260-9797-b523a5db09d1)
![image](https://github.com/iotaledger/iota-sdk/assets/45079109/4e8d8dd9-e37a-4801-afc9-c34c71496f77)

## Motivation

Without performance optimizations the UI becomes non-responsive resulting in a terrible UX.

## Are you planning to do it yourself in a pull request?
No.

**Comment by marc2332** [comment]
We have noticed that `listen_wallet is being called in every (if not every, it's close to every) call we make to any of the methods from the SDK 

![image](https://github.com/iotaledger/iota-sdk/assets/38158676/fcda8286-2185-4414-8283-88da0b763faf)

in the other hand, the "old" bindings didn't have this behavior

![image](https://github.com/iotaledger/iota-sdk/assets/38158676/85ee6fd1-b70b-4252-93f6-48410078cc24)

this is with the old bindings, notice how there is no call matching "listen"

_note: I did not test logging in when doing the performance profiling, if I did, there would probably have appeared some call matching listen, but it's not the point here anyway_

We have tried to follow the flow from when the [insert whatever method exposed from the SDK] method is called to when it's actually executed and we couldn't find any reason for it to be calling the listen_wallet method sadly

**Comment by abdulmth** [comment]
Can you maybe provide a minimal example so we can reproduce the issue locally? 

I ran the following example (create wallet, listen to all events, and `getAccount` multiple times)

```TypeScript
    initLogger();
    if (!process.env.WALLET_DB_PATH) {
        throw new Error('.env WALLET_DB_PATH is undefined, see .env.example');
    }
    try {
        const wallet = new Wallet({
            storagePath: process.env.WALLET_DB_PATH,
        });
        wallet.listen([], (e) => { console.log(e) })
        let accounts = await wallet.getAccounts();
        accounts = await wallet.getAccounts();
        accounts = await wallet.getAccounts();

        for (const account of accounts)
            console.log(account.getMetadata().alias);
    } catch (error) {
        console.error('Error: ', error);
    }
```
And added a logger on `listen_wallet` and measured the execution time of `listen_wallet` directly in the Rust code. The function was called only once and the execution time was 29.10µs.

**Comment by marc2332** [comment]
> Can you maybe provide a minimal example so we can reproduce the issue locally?
> 
> I ran the following example (create wallet, listen to all events, and `getAccount` multiple times)
> 
> ```ts
>     initLogger();
>     if (!process.env.WALLET_DB_PATH) {
>         throw new Error('.env WALLET_DB_PATH is undefined, see .env.example');
>     }
>     try {
>         const wallet = new Wallet({
>             storagePath: process.env.WALLET_DB_PATH,
>         });
>         wallet.listen([], (e) => { console.log(e) })
>         let accounts = await wallet.getAccounts();
>         accounts = await wallet.getAccounts();
>         accounts = await wallet.getAccounts();
> 
>         for (const account of accounts)
>             console.log(account.getMetadata().alias);
>     } catch (error) {
>         console.error('Error: ', error);
>     }
> ```
> 
> And added a logger on `listen_wallet` and measured the execution time of `listen_wallet` directly in the Rust code. The function was called only once and the execution time was 29.10µs.

Hey @abdulmth, we were trying to test the SDK via your example, but we couldn't get it to work. We get an empty array of accounts, even though the wallet exists, has two addresses and with funds.

![image](https://github.com/iotaledger/iota-sdk/assets/38158676/8aec855e-8d3a-4434-8501-0f49e1db2573)
![image](https://github.com/iotaledger/iota-sdk/assets/38158676/82ce21cc-5c04-4dc6-babf-0b50a528687a)
