### ISSUE TITLE
Provide option to limit requests per second

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1100]
## Description

Currently there can be > 1000 API requests per second depending on how the accounts look and what options are used, this can lead to some errors because it exceeds rate limits from the server side.
Maybe we can add a global rate limit using a crate like https://crates.io/crates/governor? Or are there other options?
We also limit our parallel requests in some places with https://github.com/iotaledger/iota-sdk/blob/4bf72ecb13c3540895d03cc62eb527241e41675a/sdk/src/client/constants.rs#L24, could this then be removed, or should we also make it modifiable by the user?

**Comment by DaughterOfMars** [comment]
Sounds like something the network admin should do as an additional layer on top of this.
