### ISSUE TITLE
Extend storage functionality (encrypt/decrypt, ...)

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#111]
## Description

Extend storage functionality with encryption as we currently have in the dev branch, might require some bigger changes to the storage module, because the current version is reduced to the basic functionality.

Transaction ids and output ids can't be used as keys in the db directly, otherwise any encryption is useless since the corresponding things can be found in the public

## Motivation

Privacy

## Requirements

1. Add options to set an encryption key
2. Be able to change the encryption key
(3. Function do "logout", which clears the encryption key and data in memory)

## Open questions (optional)

Might make sense to wait for https://github.com/iotaledger/wallet.rs/issues/806 before doing it or doing both at once

## Are you planning to do it yourself in a pull request?

No.

**Comment by Alex6323** [comment]
Having gained some experience now with it, I'ld say I can take this in an upcoming sprint.
