### ISSUE TITLE
Have readme examples as Rust examples and link to them

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1115]
## Description

Have README examples as actual code examples (without env variables) and link to them
Related to https://github.com/iotaledger/iota-wiki/issues/1139

## Motivation

So they get checked by the CI and don't get outdated

## Are you planning to do it yourself in a pull request?

No.

**Comment by Dr-Electron** [comment]
We could link to them: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

But not sure if that improves something as it has to be a permalink
