### ISSUE TITLE
Add output MIN/MAX storage deposit tests

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1120]
- [ ] [Foundry](https://github.com/iotaledger/tips-draft/blob/tip44/tips/TIP-0044/tip-0044.md#storage-deposit)
- [ ] [NFT](https://github.com/iotaledger/tips-draft/blob/tip43/tips/TIP-0043/tip-0043.md#storage-deposit)
- [ ] [Basic](https://github.com/iotaledger/tips-draft/blob/tip41/tips/TIP-0041/tip-0041.md#storage-deposit)
- [ ] [Delegation](https://github.com/iotaledger/tips-draft/blob/tip40/tips/TIP-0040/tip-0040.md#storage-deposit-calculation)
- [ ] [Account](https://github.com/iotaledger/tips-draft/blob/tip42/tips/TIP-0042/tip-0042.md#storage-deposit-calculation)

**Comment by DaughterOfMars** [comment]
Are we considering this closed by #1827 ?

**Comment by thibault-martinez** [comment]
I guess that's fine, yes
