### ISSUE TITLE
Create SC module

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#1126]
## Description

We should create something like a SC module for the SDK which wraps stuff like this: https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples/evm

## Motivation

Depositing to a chain should be something like:
```
wallet.sc.deposit(chain_address, sc_address, amount)
```

## Open questions (optional)

Should this be part of the wallet? A "submodule" of it. Which wraps everything needed for SCs

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closing as it will be done is a standalone package outside of the SDK.
