### ISSUE TITLE
Improve `call_client_method` and `call_wallet_method`

### ISSUE THREAD

**Issue by abdulmth** [iotaledger/iota-sdk#1157]
`call_client_method` and `call_wallet_method` now panic if the wallet or the client is destroyed. Investigate a way to improve this. Note that using mpsc channel was causing blocking behavior. See https://github.com/iotaledger/iota-sdk/pull/1156 .

Add the removed test if needed https://github.com/iotaledger/iota-sdk/pull/1156/files#diff-0c5d05775aa5ed1e40f101e6865a099c15b79bf8e60247eb25cb7be8e8993c68L136

**Comment by Thoralf-M** [comment]
Resolved in https://github.com/iotaledger/iota-sdk/pull/1578
