### ISSUE TITLE
Add List Outputs, Claim Outputs, and List Transactions Rust examples

### ISSUE THREAD

**Issue by jlvandenhout** [iotaledger/iota-sdk#116]
## Description

They are currently missing, while other languages do provide them.

## Motivation

Consistency.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by Thoralf-M** [comment]
Done by now
https://github.com/iotaledger/iota-sdk/blob/develop/sdk/examples/how_tos/accounts_and_addresses/list_outputs.rs
https://github.com/iotaledger/iota-sdk/blob/develop/sdk/examples/how_tos/advanced_transactions/claim_transaction.rs
https://github.com/iotaledger/iota-sdk/blob/develop/sdk/examples/how_tos/accounts_and_addresses/list_transactions.rs
