### ISSUE TITLE
Python use int for u64 values

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1163]
## Description

Python use int for u64 and u128 values https://github.com/iotaledger/iota-sdk/pull/1152#discussion_r1317234431
So change serialization to convert the types

Can probably use something like this for affected fields
```
 = field(metadata=config(
                      decoder=int_from_str
                      encoder=int_to_str
                  ))
```

## Motivation

Usability 

## Requirements

1. Update types and add custom de/serialization for the affected fields

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1402
