### ISSUE TITLE
Python deserialization fails for union types

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1164]
## Description

Deserialization fails for union types if the data is not always matching the first type.
For example `address: Ed25519Address | AliasAddress | NFTAddress` only works if the type matches the `Ed25519Address` variant, for `AliasAddress` or `NFTAddress` an error is returned.

Didn't found a solution yet, but maybe can be done with something similar to this
```Python
    # https://github.com/lidatong/dataclasses-json/issues/303
    address: Ed25519Address | AliasAddress | NFTAddress = field(
        metadata=config(
            decoder=lambda d: 
            match d["type"]:
                    case AddressType.Ed25519:
                        Ed25519Address.from_dict(d)
                    case ...
``` 
If not probably a custom `_from_dict_custom()`, similar to https://github.com/iotaledger/iota-sdk/blob/1add7b796dd964a153a253e29cd06af7d5e8900e/bindings/python/iota_sdk/types/transaction_options.py#L31 can be used

`https://github.com/lidatong/dataclasses-json/pull/478 might help`

## Motivation

Make deserialization work correct

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Only happening in 2.0?

**Comment by Thoralf-M** [comment]
Yes, most probably introduced in https://github.com/iotaledger/iota-sdk/commit/80a5667ba740a3c574e2b833d5be69f83c19f51b

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1335
