### ISSUE TITLE
Add Client::post_request_bytes

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1185]
We have
- get_request
- get_request_bytes
- post_request_json

But not post_request_bytes.

Also maybe drop than json prefix on post_request ?

**Comment by DaughterOfMars** [comment]
I didn't add it because it wasn't used 🤷‍♀️

**Comment by thibault-martinez** [comment]
> I didn't add it because it wasn't used 🤷‍♀️

We need it in 2.0

**Comment by DaughterOfMars** [comment]
Ah!

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1214
