### ISSUE TITLE
CI: Enable pylint for code

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#1236]
## Description

Currently pylint only tests examples

## Motivation

more ci is better

## Requirements

1. Update python tox.ini and add pylint --rcfile=examples/.pylintrc iota_sdk/**/*.py
2. Optionally move the `.pylintrc` to base folder
3. Fix errors or mute em

**Comment by kwek20** [comment]
Also address https://github.com/iotaledger/iota-sdk/pull/1239#discussion_r1330027547

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1315
