### ISSUE TITLE
Add `/outputs` indexer route and QueryParameter::UnlockableByAddress

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1241]
## Description

Add `/outputs` indexer route with `unlockableByAddress` filter

## Motivation

This new route makes it possible to get outputs with different type that can be unlocked by the provided address with the new filter with a single request

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1246
