### ISSUE TITLE
Have specific structs for the QueryParameters

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1248]
## Description

Have more specific enums for the QueryParameters, so for each route one can only provide query parameters that can actually be used there, like in the nodejs binding.

- [x] Rust
- [ ] Nodejs
- [ ] Python

## Motivation

https://github.com/iotaledger/iota-sdk/pull/1246#discussion_r1328690716

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1428
