### ISSUE TITLE
Rename vByteFactorIssuerKeys to vByteFactorBlockIssuerKey

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1262]
https://github.com/iotaledger/tips-draft/pull/24/files/f005d5a0949de987c481dc3a54cb35e1345ae375..0f9aa6e2277e788f2d5438b20dac6e303dfc435f

- [x] Rust
- [x] Python
- [x] Nodejs

**Comment by Alex6323** [comment]
seems like this was done already in #1265

**Comment by thibault-martinez** [comment]
> seems like this was done already in #1265

What about Python?

**Comment by Alex6323** [comment]
Brord seems to have done it last week with #1276

**Comment by thibault-martinez** [comment]
Not relevant anymore.
