### ISSUE TITLE
Remove excess dependency features from 2.0

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/iota-sdk#1275]
## Description

There are many features in the SDK that are created by dependencies that should be removed, as they are polluting the feature space. They should be removed at 2.0 since this is a breaking change.
- `url`
- `instant`
- `iota-ledger-nano`
- `serde_repr`
- `regex`
- `rumqttc`
- `rand` (the feature is just a wrapper)
- `bs58`
- `iota_stronghold`
- `thiserror`
- `futures`
- `tokio`
- `zeroize`
- `reqwest`
- `async-trait`
- `log`

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1278
