### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by drtwodog** [iotaledger/iota-sdk#1285]
### Issue description

I want to send some basic token "rms" from an NFT to my wallet.

NFT:
senderAddress 0x75fde2b587d3ba0816e0bd8ec752a0e3457aa6386264e3068d4e062d824aa57d
senderAddressBech32 rms1zp6lmc44slfm5zqkuz7ca36j5r35274x8p3xfccx348qvtvzf2jh6wfm5qr

Wallet: 
receiverAddress rms1qq885778p3ng3kfkmjtgezvwn4hg8aulycf4snvxwe6vcttuax2gwmynykx

I used the coding similar to the one as given in the examples: (alias_wallet/transaction)

> 
           const queryParameters = [

                {
                    address: senderAddressBech32,   //my NFT
                },
            ];
           
            const inputs = ( await (await wallet.getClient()).basicOutputIds(queryParameters) ).items;
            
       //inputs  / basicOutputId is
         // [
        //    '0xdd9d1d0b95d364941ef4257b21cbf736566174d7fa4be7cd9f321dcd9293d47e0000'
       //   ]
                  
           const params = [
                {
                    address: receiverAddress, //->my Wallet address
                    amount: AmounttoSend,  //e.g. 1 -> BigInt
                },
            ];
            const options = {
                mandatoryInputs: inputs,
                allowMicroAmount: false,
            };

            const transaction = await account.sendWithParams(params, options);

            await account.retryTransactionUntilIncluded(transaction.transactionId);
            console.log(
                `Transaction with custom input: https://explorer.iota.org/testnet/transaction/${transaction.transactionId}`,
            );

The Error is:
{
  type: 'wallet',
  error: '`required input 0xdd9d1d0b95d364941ef4257b21cbf736566174d7fa4be7cd9f321dcd9293d47e0000 is not available`'
}

But the output is visible in the https://explorer.shimmer.network/testnet/
What is wrong (maybe with me :-)) ? Could you help me?

### Version

 "@iota/sdk": "^1.0.11",

### Expected behaviour

Funds are transfered from NFT to my Wallet

### Actual behaviour

Error

### Can the issue reliably be reproduced?

Yes

### Errors

{
  type: 'wallet',
  error: '`required input 0xdd9d1d0b95d364941ef4257b21cbf736566174d7fa4be7cd9f321dcd9293d47e0000 is not available`'
}

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Did you provide `NftSyncOptions` with `basicOutputs: true` when syncing?

**Comment by drtwodog** [comment]
Hey Thoralf,

Thank you again ... that was exactly the problem :-)
-> But with that I completly take te respective output(s) and its complete value(s). Is it possible to just take a specific amount of the output(s)?

Regards,
Andreas

**Comment by Thoralf-M** [comment]
One always has to completely consume an output, not possible to only take a part of it. However you can just create a new output with the same unlock conditions/features... just with less amount (as long as it's >= than required for the storage deposit), which is then basically the same as taking only a part

**Comment by drtwodog** [comment]
Ahhh... ok ... that is what i finaly did! Super -> A big thx again!

**Comment by thibault-martinez** [comment]
> Ahhh... ok ... that is what i finaly did! Super -> A big thx again!

All good then? Can this be closed?

**Comment by drtwodog** [comment]
Of course
