### ISSUE TITLE
QA: Make sure all bindings are properly typed

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#129]
- [x] Python
- [x] Nodejs

**Comment by Dr-Electron** [comment]
Python: 

- [x] generate_addresses_options  in consolidate_funds https://github.com/iotaledger/iota-sdk/pull/683
- [x] TransactionOptions for different functions https://github.com/iotaledger/iota-sdk/pull/640
- [x] All Params of different send or prepare functions https://github.com/iotaledger/iota-sdk/pull/783
- [x] client_options in Wallet constructor https://github.com/iotaledger/iota-sdk/pull/805
- [x] In some places we don't "typehint" the secret_manager with `secret_manager: Optional[LedgerNanoSecretManager | MnemonicSecretManager | StrongholdSecretManager]` https://github.com/iotaledger/iota-sdk/pull/683
- [x] sync options https://github.com/iotaledger/iota-sdk/pull/707

Nodejs seems fine, so I guess was should be too. 
Java is not a thing anymore and swift won't be in our repo, right?

**Comment by Thoralf-M** [comment]
> In some places we don't "typehint" the secret_manager with secret_manager: Optional[LedgerNanoSecretManager | MnemonicSecretManager | StrongholdSecretManager]

Can this be done with SecretManagerType alias or something like that? We have a `SecretManager` class which is different, so that name we can't use :thinking:

**Comment by Dr-Electron** [comment]
> > In some places we don't "typehint" the secret_manager with secret_manager: Optional[LedgerNanoSecretManager | MnemonicSecretManager | StrongholdSecretManager]
> 
> Can this be done with SecretManagerType alias or something like that? We have a `SecretManager` class which is different, so that name we can't use 🤔

You could create an Alias for all types. But why would you want to do that? Can't we just use this in every function where a secret_manager can be passed?

So something like:
```python
function_with_secret_manager(secret_manager: Optional[LedgerNanoSecretManager | MnemonicSecretManager | StrongholdSecretManager])
```

**Comment by Thoralf-M** [comment]
Sure we can do that, just is very large to always have all

**Comment by Dr-Electron** [comment]
Yeah true. But I prefer it, as it clearly shows all options 🤔

**Comment by thibault-martinez** [comment]
Python:

These needs to be objects, not dicts
- [x] The Transaction returned by send functions https://github.com/iotaledger/iota-sdk/pull/783
- [x] Block returned by get_block_data https://github.com/iotaledger/iota-sdk/pull/709
- [x] Signature returned by sign_ed25519 https://github.com/iotaledger/iota-sdk/pull/746
- [x] Addresses returned by account.addresses https://github.com/iotaledger/iota-sdk/pull/792

**Comment by thibault-martinez** [comment]
Python: `build_and_post_block`'s param shouldn't be a `SendAmountParams` https://github.com/iotaledger/iota-sdk/pull/783

**Comment by Thoralf-M** [comment]
- [x] Account::prepare_output() https://github.com/iotaledger/iota-sdk/pull/799
- [x] Wallet::set_client_options() https://github.com/iotaledger/iota-sdk/pull/805
- [x] Account::unspent_outputs() FilterOptions https://github.com/iotaledger/iota-sdk/pull/799
- [x] Account::sign_transaction_essence() https://github.com/iotaledger/iota-sdk/pull/812
- [x] Account::sign_and_submit_transaction() https://github.com/iotaledger/iota-sdk/pull/812
- [x] Account::submit_and_store_transaction() https://github.com/iotaledger/iota-sdk/pull/812
- [x] SecretManager::generate_evm_addresses() parms type hints https://github.com/iotaledger/iota-sdk/pull/799
- [x] SecretManager::sign_transaction() https://github.com/iotaledger/iota-sdk/pull/812
- [x] Client::prepare_transaction() https://github.com/iotaledger/iota-sdk/pull/812
- [x] Client::sign_transaction() https://github.com/iotaledger/iota-sdk/pull/812
- [x] Client::submit_payload() https://github.com/iotaledger/iota-sdk/pull/812
- [x] Client::get_network_info() https://github.com/iotaledger/iota-sdk/pull/799
- [x] TransactionPayload essence and unlocks https://github.com/iotaledger/iota-sdk/pull/812
- [x] UtxoChanges type https://github.com/iotaledger/iota-sdk/pull/825
- [x] Signature type https://github.com/iotaledger/iota-sdk/pull/825
- [x] TransactionEssence type https://github.com/iotaledger/iota-sdk/pull/825
- [x] Client::prepare_transaction() options https://github.com/iotaledger/iota-sdk/pull/825
