### ISSUE TITLE
Expose Output serialization

### ISSUE THREAD

**Issue by msarcev** [iotaledger/iota-sdk#1293]
## Description

Currently there is a need in Firefly for a way to serialize an `Output` and get back the bytes or hex encoded bytes.
I'm not sure if we should expose this for all models, or some parts, currently we only need it for `Output`

## Motivation

The need comes from the Firefly integration with ShimmerEVM and the `estimategas-onledger` endpoint.
https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/wasp/develop/clients/apiclient/api/openapi.yaml
This endpoint required the serialized `outputBytes` to be sent in the body of the request for the estimation.

## Requirements

Write a list of what you want this feature to do.

1. Allow iota-sdk to be used to get the result of `Output` serialization.

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1308
