### ISSUE TITLE
Optimize clearStrongholdPassword

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/iota-sdk#1297]
## Description

Currently `clearStrongholdPassword()` on the `Wallet` class of the nodeJS bindings takes ~2 sec to finish. This should be optimized.

## Motivation

UX degrades heavily for calls that don't finish below 100ms.

## Requirements

`clearStrongholdPassword()` finishes in <100 ms

## Are you planning to do it yourself in a pull request?

No.

**Comment by kwek20** [comment]
Happens on both rust and nodejs, investigating further now

**Comment by thibault-martinez** [comment]
Closing as there is nothing we can do in the SDK itself. The encryption/encoding of the new stronghold simply is way slower than before. Any improvement, if even possible, would have to be done there.
