### ISSUE TITLE
Handle mana rewards in Delegation Output destruction 

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1310]
https://github.com/iotaledger/tips-draft/blob/tip40/tips/TIP-0040/tip-0040.md#consumed-outputs

- [ ] https://github.com/iotaledger/iota-sdk/pull/1700/files#diff-0cd9fdcd945509b7f15ba76e36be88c3db111d6c0967dd15327efe148d5a9421R194
- [ ] https://github.com/iotaledger/iota-sdk/pull/1831/files#diff-d902708cabe60524f3e8b5aa7a1d9d469085e72150ee311dffe15f53d175bb63R133

**Comment by DaughterOfMars** [comment]
@Thoralf-M is this fixed by #1421?

**Comment by Thoralf-M** [comment]
No, the PR is only adding validation logic, this issue here is about adding the mana to an output

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1906
