### ISSUE TITLE
[Bug]: Created Output but it is send to a wrong address

### ISSUE THREAD

**Issue by drtwodog** [iotaledger/iota-sdk#1321]
### Issue description

I want to create an Basic aoutput with Amount for an NFT (SMR Testnet)
MY NFT:
receiverAddressBech32   rms1zz4lcntprddwp26d69z6y50uq2thqsv5vzydjyaexxaqwzl5sk7q62v0hk8
hexReceiver                      0xabfc4d611b5ae0ab4dd145a251fc02977041946088d913b931ba070bf485bc0d

MyWallet
senderAddressBech32      rms1qz8az4zfuxxtqjmyd3tpnwhl37gsn3gdrhx0kc6hgqv229qh5r59q90awxr
hexSender                        0x8fd15449e18cb04b646c5619baff8f9109c50d1dccfb63574018a51417a0e850

        const syncOptions = {
            nft: {
                basicOutputs: true,
            },
        };
       
        const balance = await account.sync();
        const hexReceiver = Utils.bech32ToHex(receiverAddressBech32,);
        const hexSender = Utils.bech32ToHex(senderAddressBech32,);

        console.log("receiverAddressBech32", receiverAddressBech32);
        console.log("hexReceiver", hexReceiver);
        console.log("senderAddressBech32", senderAddressBech32);
        console.log("hexSender", hexSender);

        
        const addressUnlockCondition: UnlockCondition = new AddressUnlockCondition(new Ed25519Address(hexReceiver)); //NFT

        console.log("addressUnlockCondition", addressUnlockCondition);
        
        const basicOutput = await client.buildBasicOutput({
            amount: realAmounttoSend,
            unlockConditions: [addressUnlockCondition],
            features: [
                new TagFeature(utf8ToHex('Fund')),
                new SenderFeature(new Ed25519Address(hexSender))]
        }); 
        
        
          
        transaction = await account.sendOutputs([basicOutput]);
 
       console.log('Waiting until included in block...');
        const blockId = await account.retryTransactionUntilIncluded(
            transaction.transactionId,
        );
        console.log(`Block sent: ${process.env.EXPLORER_URL}/block/${blockId}`);

The output look ok for me -> Even with the addresses:
basicOutput {
  "type": 3,
  "amount": "22000000",
  "unlockConditions": [
    {
      "type": 0,
      "address": {
        "type": 0,
        "pubKeyHash": "0xabfc4d611b5ae0ab4dd145a251fc02977041946088d913b931ba070bf485bc0d"
      }
    }
  ],
  "features": [
    {
      "type": 0,
      "address": {
        "type": 0,
        "pubKeyHash": "0x8fd15449e18cb04b646c5619baff8f9109c50d1dccfb63574018a51417a0e850"
      }
    },
    {
      "type": 3,
      "tag": "0x46756e64"
    }
  ]
}

But if you look to the transaction / Block
Transaction sent: 0xeafa9c7aff3b5b68e216e806bd30eb4bdd84e09f67bef458bca4236588f54116
Waiting until included in block...
Block sent: https://explorer.shimmer.network/testnet/block/0x7a21b2beed476ee10734cdb13b9508623b3adaa05c1e4406e6258a385b4a908d

-> The Unlockcondition point at a strange address: 
rms1qz4lcntprddwp26d69z6y50uq2thqsv5vzydjyaexxaqwzl5sk7q6a6xa9j   -> I expected that the amount is send to the address of the NFT

BTW: I have to use iota/sdk 1.0.8 -> Because in .10 & .11 the wallet.destroy() operation is not working as before ... (is this known)?

### Version

iota/sdk nodejs 1.0.8 (1.0.10 & 1.0.11 -> The Wallet.destroy() is not working if I e.g. refresh my page -> and make a new selection)

### Expected behaviour

Assign output to my NFT
MY NFT:
receiverAddressBech32   rms1zz4lcntprddwp26d69z6y50uq2thqsv5vzydjyaexxaqwzl5sk7q62v0hk8
hexReceiver                      0xabfc4d611b5ae0ab4dd145a251fc02977041946088d913b931ba070bf485bc0d

### Actual behaviour

-> The Unlockcondition point at a specific address: 
rms1qz4lcntprddwp26d69z6y50uq2thqsv5vzydjyaexxaqwzl5sk7q6a6xa9j   -> I expected that the amount is send to the address of the NFT

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
`new AddressUnlockCondition(new Ed25519Address(hexReceiver)); //NFT` is the wrong part since it's not an Ed25519 address, needs to be `new AddressUnlockCondition(new NftAddress(hexReceiver)); //NFT`

**Comment by drtwodog** [comment]
ahhh...-> thx
