### ISSUE TITLE
Bindings ProtocolParameters tests

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#1338]
## Description

Similar to https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/tests/types/protocol.rs

As requested here: https://github.com/iotaledger/iota-sdk/pull/1276#pullrequestreview-1635667286

## Motivation

We want to validate that the node sends us the protocol parameters we expect on all bindings

## Requirements

- [x] Nodejs
- [x] Python

## Open questions

- What is the purpose of this test in bindings after the protocol parameters are finalized?

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1508
