### ISSUE TITLE
Handle new address types matches

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/iota-sdk#1354]
## Description

The new address types (ImplicitAccount, Multi, Restricted) must be handled in the areas where we match on addresses. This may mean creating a new error, or using them properly within the context.

- [x] https://github.com/iotaledger/iota-sdk/pull/1229/files#diff-69bb87d0b10ec0b295b4d7c556aed261ad8583ec45dda1808779f3ad2cb998e8R51 (https://github.com/iotaledger/iota-sdk/pull/1680)
- [x] https://github.com/iotaledger/iota-sdk/pull/1229/files#diff-1e98e5f88fd2b322d83ada052273cbadce18bec4d2221296ced35927337c83f8R547 (https://github.com/iotaledger/iota-sdk/pull/1768)
- [x] https://github.com/iotaledger/iota-sdk/pull/1229/files#diff-4837978b4d3d1c2f1b96b18e96e29ec5a50a32867735eb9bee9981528b888d5fR535 (https://github.com/iotaledger/iota-sdk/pull/1768)
- [x] required_account_nft_addresses (https://github.com/iotaledger/iota-sdk/pull/1743)
- [x] In Unlock address (https://github.com/iotaledger/iota-sdk/pull/1678)

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1768
