### ISSUE TITLE
Cleanup Nodejs env var checks in examples

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1359]
Same as https://github.com/iotaledger/iota-sdk/issues/1358, but for Nodejs and in many examples there are also checks missing in the first place, so they should be added before (for example process.env.EXPLORER_URL)

**Comment by shreykul** [comment]
Can you assign this to me please?

**Comment by Thoralf-M** [comment]
The merged PR didn't do it for all examples, for example here it still needs to be done https://github.com/iotaledger/iota-sdk/blob/b3f77d5a7a655741b3317a15997beef825062895/bindings/nodejs/examples/client/05-get-address-balance.ts#L14-L26
Also modified the issue description to now add also missing checks

**Comment by raprocks** [comment]
is someone still working on this? if not please let me know :)

**Comment by Thoralf-M** [comment]
Currently not, do you want me to assign you?

**Comment by raprocks** [comment]
sure @Thoralf-M , that would be good, let me know what more needs to be done on the existing changes and i would be happy to review them too

**Comment by Thoralf-M** [comment]
@raprocks it's about going through the examples https://github.com/iotaledger/iota-sdk/tree/develop/bindings/nodejs/examples and find remaining ones like in the screenshot with two or more individual checks for env values 
![image](https://github.com/iotaledger/iota-sdk/assets/46689931/6c28002f-72a2-4b0c-a302-75f2d2faa436)
and merge them like this
```
    for (const envVar of [
        'FAUCET_URL',
        'WALLET_DB_PATH',
        'STRONGHOLD_PASSWORD',
    ])
        if (!(envVar in process.env)) {
            throw new Error(`.env ${envVar} is undefined, see .env.example`);
        }
```
and in some other files process.env values are used for which the check is completely missing like process.env.EXPLORER_URL here, this then also needs to be added/merged
![image](https://github.com/iotaledger/iota-sdk/assets/46689931/dd19766f-c304-4248-a847-adcbcb00cbe5)

**Comment by raprocks** [comment]
just a quick recommendation, this throws error for every a missing variable exclusively instead of a list of missing variables, isnt it better to update the error?

**Comment by raprocks** [comment]
```javascript 
    const missingVars = [];
    for (const envVar of [
        'FAUCET_URL',
        'WALLET_DB_PATH',
        'STRONGHOLD_PASSWORD',
    ])
        if (!(envVar in process.env)) {
            missingVars,push(envVar);
        }
     if (missingVars.length > 0){
     throw new Error(`.env ${envVar} is undefined, see .env.example`);
     }
```
for example

**Comment by DaughterOfMars** [comment]
Something like that may be nice, but of course there are many many files that would have to be updated. For now, I would suggest moving forward with the current plan.

**Comment by raprocks** [comment]
Got it. Will move ahead with it.

**Comment by raprocks** [comment]
Should be good to close this issue :) #1386
