### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by drtwodog** [iotaledger/iota-sdk#1361]
### Issue description

Hey,

Wallet/Account1:
I Created a NFT ( "A" ) and assigned another NFT ( "B" ) to it  (so far so good) -> I can defenetly send from that NFT the assigned NFT back to the Wallet.

Now I send the NFT ("A") to a different Wallet/Account2.
-> Sending is possible
-> BUT to extract/unassing the NFT ("B") from NFT ("A") is now not Possible:
Error:  { type: 'wallet', error: 'nft not found in unspent outputs' }

Is there a way/ example how to send the unspend outputs (as unspendOutputs)? 

Currently I´m sending the NFT with 
            const outputs: SendNftParams[] = [
                {
                    address: toAddress,
                    nftId: NftToSend
                },
            ];

### Version

@iota/sdk": "^1.0.8"

### Expected behaviour

Send the NFT to a different wallet with included NFTs. In the new wallet it could be extracted etc.

### Actual behaviour

Send "Header NFT" -> But in the differen Wallet/Account the assignet NFT could not be extracted -> (Error:  { type: 'wallet', error: 'nft not found in unspent outputs' }

### Can the issue reliably be reproduced?

Yes

### Errors

Error:  { type: 'wallet', error: 'nft not found in unspent outputs' }

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Did you provide `NftSyncOptions` with `nftOutputs: true` when syncing? By default its false

**Comment by drtwodog** [comment]
Ok, again the problem sits 30 cm befor the screen ... :-)
By the way! You did /do a great job! And the support times (e.g. Saturday...like here) are not self-evident... Thank you again!!!
