### ISSUE TITLE
Python: fix some tests (and remove corresponding `pytest` ignore)

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#1387]
- [x] `test_address_generation_iota`
- [x] `test_address_generation_shimmer`
- [x] `test_basic_block_with_tx_payload`
- [x] `test_basic_block_with_tx_payload_all_output_types`
- [x] `test_basic_block_with_tx_payload_with_tagged_data_payload`
- [x] `test_sign_verify_ed25519`
- [x] `test_wallet_destroy`

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1931
