### ISSUE TITLE
Add Python 3.12 to release workflow

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1403]
Add Python 3.12 to release workflow so we also build wheels for this version
https://github.com/iotaledger/iota-sdk/blob/4883f7c7e7d304254825ceba1d37ebbdc61b8ab7/.github/workflows/bindings-python-publish.yml#L14

**Comment by sid-js** [comment]
@Thoralf-M Can I please work on this ? If yes please assign it to me :)
