### ISSUE TITLE
What version of the crate to use after the upgrade to Stardust?

### ISSUE THREAD

**Issue by f-squirrel** [iotaledger/iota-sdk#1415]
### Issue description

I tried to use version 1.1.0, but it doesn't work with the public node: https://api.stardust-mainnet.iotaledger.net/api/core/v2/.
The only one that seems to work is the "develop" branch, which was initially for Shimmer.

Is this the right version?
If yes, is it not expected to be "production"?

### Version

1.1.0

### Expected behaviour

To be compatible

### Actual behaviour

`thread 'main' panicked at 'Got an unexpected error'`

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
`thread 'main' panicked at 'Got an unexpected error'`
Any code to reproduce this? Shimmer and IOTA now run with the stardust protocol, so the library can be used for both
1.1 should work fine and develop as well, we just didn't update all the branches yet

**Comment by f-squirrel** [comment]
> `thread 'main' panicked at 'Got an unexpected error'` Any code to reproduce this? Shimmer and IOTA now run with the stardust protocol, so the library can be used for both 1.1 should work fine and develop as well, we just didn't update all the branches yet

Sure, this is an example.


```rust
        let client =
            Client::builder() // Create a client instance builder
                .with_node("https://api.stardust-mainnet.iotaledger.net/api/core/v2/")
                .expect("Failed to build client")
                .finish()
                .await
                .expect("Failed to build client");

        let node_info = client.get_info().await.unwrap().nodeinfo;
```

Traceback:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NodeError("Couldn't get a result from any node")':
```

More info about the SDK version:

```toml
[[package]]
name = "iota_client"
version = "0.1.0"
dependencies = [
 "iota-client 1.4.0",
]
```

**Comment by Thoralf-M** [comment]
You're importing iota_client, not iota_sdk
Use
```
[dependencies]
iota-sdk = "1.1.0"
```
and for the node url provide just `https://api.stardust-mainnet.iotaledger.net`, not with the `/api/core/v2/`

**Comment by f-squirrel** [comment]
Thank you @Thoralf-M !
