### ISSUE TITLE
feature: Typed errors in NodeJS bindings

### ISSUE THREAD

**Issue by marc2332** [iotaledger/iota-sdk#1417]
## Description

Support typed errors in the NodeJS Bindings.

## Motivation

It allows us (Firefly) to always have up-to-date error types that match the SDK.

## Requirements

1. Have typed-errors from the SDK in the NodeJS bindings.

## Are you planning to do it yourself in a pull request?

Maybe. I'll investigate myself and update this issue accordingly.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1858
