### ISSUE TITLE
Add ContextInputs wrapper?

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1422]
## Description

Add ContextInputs wrapper, a struct with each variant of the enum as optional field?
`UnlockConditions` for `UnlockCondition` enum could also be changed?

https://github.com/iotaledger/iota-sdk/pull/1421/files#r1356721700

**Comment by Alex6323** [comment]
We decided to close this issue for the following reasons:
(1) this change isn't doable for ContextInputs since you can have mutlitple Reward context inputs
(2) the refactor is just too intense to justify the benefits at the current moment (we can reconsider later)
