### ISSUE TITLE
[Bug]: Node endpoint is truncated after hostname 

### ISSUE THREAD

**Issue by HolgerKoether** [iotaledger/iota-sdk#1444]
### Issue description

When using the SDK and entering a node endpoint, the string is cut/truncated after the hostname, e.g.
node.xyz.com/aaa-bbb-ccc is truncated to node.xyz.com
It is a common feature for infrastructure service providers to provide access not only via auth. header (this works in the SDK) but also directly through a customer specific endpoint like aaa-bbb-ccc (which usually reflects an API key).

Infura and many other service providers are offering this way. Please add capability to use node/endpoint names like "node.xyz.com/aaa-bbb-ccc" in the SDK.

### Version

latest

### Expected behaviour

node name is accepted by SDK in format of node.xyz.com**/aaa-bbb-ccc**

### Actual behaviour

node name like node.xyz.com/aaa-bbb-ccc is not accepted/working

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
Hi @HolgerKoether, thanks for the report. Are you able to check if https://github.com/iotaledger/iota-sdk/pull/1476 solves your issue ? Thanks in advance.
