### ISSUE TITLE
get_included_block returns an error for tx id

### ISSUE THREAD

**Issue by f-squirrel** [iotaledger/iota-sdk#1465]
### Issue description

I am trying to get a block by transaction ID as follows:

```rust
for transaction in unique_transactions {
    let transaction_data = client
        .get_included_block(&transaction)
        .await
```

I tried to do the same against several public nodes, but all of them returned the same error.

Do I miss something, or is it a bug?

### Version

1.1.0

### Expected behaviour

I expect to receive a block.

### Actual behaviour

An error is returned:

```
 NotFound(
        "https://api.stardust-mainnet.iotaledger.net/api/core/v2/transactions/0xc74466f2310c4c3c2563f6d6d24f5cb5dc3b33583dbbb2b4cc4de44cb656098e/included-block",
    ),
```

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
Hello, that's not a bug, this transaction happened in the chrysalis mainnet so it's not available in the new stardust mainnet.
You can find it here https://explorer.iota.org/chrysalis-mainnet/message/c74466f2310c4c3c2563f6d6d24f5cb5dc3b33583dbbb2b4cc4de44cb656098e.

**Comment by f-squirrel** [comment]
> Hello, that's not a bug, this transaction happened in the chrysalis mainnet so it's not available in the new stardust mainnet. You can find it here https://explorer.iota.org/chrysalis-mainnet/message/c74466f2310c4c3c2563f6d6d24f5cb5dc3b33583dbbb2b4cc4de44cb656098e.

Does it mean that the new protocol does not support fetching the history data?
How is it possible?

**Comment by thibault-martinez** [comment]
> > Hello, that's not a bug, this transaction happened in the chrysalis mainnet so it's not available in the new stardust mainnet. You can find it here https://explorer.iota.org/chrysalis-mainnet/message/c74466f2310c4c3c2563f6d6d24f5cb5dc3b33583dbbb2b4cc4de44cb656098e.
> 
> Does it mean that the new protocol does not support fetching the history data? How is it possible?

That's correct, chrysalis and stardust are not compatible protocols.

**Comment by f-squirrel** [comment]
> > > Hello, that's not a bug, this transaction happened in the chrysalis mainnet so it's not available in the new stardust mainnet. You can find it here https://explorer.iota.org/chrysalis-mainnet/message/c74466f2310c4c3c2563f6d6d24f5cb5dc3b33583dbbb2b4cc4de44cb656098e.
> > 
> > 
> > Does it mean that the new protocol does not support fetching the history data? How is it possible?
> 
> That's correct, chrysalis and stardust are not compatible protocols.

But new blocks in Stardust point to transactions from Crysalis and these transactions are not fetchable!
Is there a way to fetch block together with all transactions and input/outputs?

**Comment by thibault-martinez** [comment]
> > > > Hello, that's not a bug, this transaction happened in the chrysalis mainnet so it's not available in the new stardust mainnet. You can find it here https://explorer.iota.org/chrysalis-mainnet/message/c74466f2310c4c3c2563f6d6d24f5cb5dc3b33583dbbb2b4cc4de44cb656098e.
> > > 
> > > 
> > > Does it mean that the new protocol does not support fetching the history data? How is it possible?
> > 
> > 
> > That's correct, chrysalis and stardust are not compatible protocols.
> 
> But new blocks in Stardust point to transactions from Crysalis and these transactions are not fetchable! Is there a way to fetch block together with all transactions and input/outputs?

Outputs kept their ID which include the Transaction ID, yes.
No there is no such way, if you want to fetch transactions from the chrysalis mainnet, you will have to use a chrysalis library.

**Comment by thibault-martinez** [comment]
Do you have any more question on the topic @f-squirrel ?

**Comment by f-squirrel** [comment]
@thibault-martinez , thank you very much for your answers. I do have more questions :)

1. What do you mean by "use a chrysalis library"? Do you mean the deprecated [iota.rs crate](https://github.com/iotaledger/iota.rs)?
2. Shall I use iota.rs crate to connect to the stardust node or only to a chrysalis node to get the old data?

**Comment by thibault-martinez** [comment]
> @thibault-martinez , thank you very much for your answers. I do have more questions :)
> 
> 1. What do you mean by "use a chrysalis library"? Do you mean the deprecated [iota.rs crate](https://github.com/iotaledger/iota.rs)?
> 2. Shall I use iota.rs crate to connect to the stardust node or only to a chrysalis node to get the old data?

1. Yes
2. iota.rs for chrysalis nodes, iota-sdk for stardust nodes

**Comment by thibault-martinez** [comment]
Do you have any more questions?

**Comment by f-squirrel** [comment]
@thibault-martinez , no, thank you!
