### ISSUE TITLE
Change _to_dict_custom() to class method?

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1473]
## Description

Currently it's a static method which accepts a dict which gets created here https://github.com/iotaledger/iota-sdk/blob/346b6c897596607f9564483956ab6b7393fee04e/bindings/python/iota_sdk/types/common.py#L21-L29

Related comment https://github.com/iotaledger/iota-sdk/pull/1381/files/019aa6e73b16adc26cfafec138f8c6e6b5fb96fa..86d678be049d37c7e2e4b809a14a9641bb1266df#r1364408452

## Open questions (optional)

It should probably be just a class method which accepts `cls` as parameter, or is there any reason why it's not that?

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1482
