### ISSUE TITLE
Reconsider what should be part of SecretManager or not

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1490]
Should this be part of the Trait? Seems kind of weird. Maybe we should just remove both.

_Originally posted by @DaughterOfMars in https://github.com/iotaledger/iota-sdk/pull/1483#discussion_r1368646716_

**Comment by thibault-martinez** [comment]
Should probably keep the trait to a minimum.
Maybe have a SecretManagerExt if needed.

**Comment by DaughterOfMars** [comment]
The alternative cannot be part of the secret manager, because we would still need the bounds on generic types. If we remove anything it would have to be a function that takes a secret manager, perhaps on the wallet or something.
