### ISSUE TITLE
Fix nodejs examples npm install

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1491]
`npm i` in `iota-sdk/bindings/nodejs/examples` fails with 
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../
```

**Comment by Thoralf-M** [comment]
The merged PR actually didn't fix it (I think it only worked because something was still cached)
When rebuilding it either fails with yarn or npm, never got it working with both

**Comment by Thoralf-M** [comment]
We decided to use yarn everywhere https://github.com/iotaledger/iota-sdk/pull/1953
