### ISSUE TITLE
Python use int for u128 values 

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1494]
## Description

Python use int for u128 values, similar to https://github.com/iotaledger/iota-sdk/issues/1163, just that u128 is encoded as HexStr instead of a normal string

- [ ] https://github.com/iotaledger/iota-sdk/pull/1482/files#r1370711780

## Motivation

Easier to use

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1552
