### ISSUE TITLE
Update application/vnd.iota.serializer-v1 to v2

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1497]
## Description

Update application/vnd.iota.serializer-v1 to v2 https://github.com/iotaledger/iota-sdk/blob/3dc6d56360ec96591ad8565b8dcdb77a53ac3ede/sdk/src/client/node_manager/http_client.rs#L99-L117 (note: should be done only for the 2.0 branch)

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1527
