### ISSUE TITLE
[Bug]: Unable to fetch outputs with 

### ISSUE THREAD

**Issue by brancoder** [iotaledger/iota-sdk#1502]
### Issue description

Not able to fetch output data with `account.getOutput(outputId)`,  for the first transaction made to the `ShimmerEVM Testnet` from FF.
1. [Transaction](https://explorer.shimmer.network/testnet/transaction/0xbf388cd5442b5afd9c7c246b78b4ad71e86834a559bd0befab4cbdb295e1f5d4) of 50 native tokens to ShimmerEVM Testnet: 

In FireFly if we do `account.getOutput(outputId)`  for first output in this tx
 with outputId: `0xbf388cd5442b5afd9c7c246b78b4ad71e86834a559bd0befab4cbdb295e1f5d40000`  and the result is `null`
output in question has:

- Address Unlock Condition => Alias address
- Expiration UC=> rms1qzezp3th8yrsrukh8jtlme4v23zqdm94hmrxf4dnj05exltt0jm75xc753j (sender address)
- Sender
- Metadata

2. [Second transaction ](https://explorer.shimmer.network/testnet/transaction/0xbfc02b2aedb355e97195336682f42185f21c1fc00cb6e9a43436370e36f2425c) of 6000 native tokens to Wallet 1 address: 
In FireFly if we do `account.getOutput(outputId)`  for first output in this tx with outputId: `0xbfc02b2aedb355e97195336682f42185f21c1fc00cb6e9a43436370e36f2425c0000`  we DO get output details as result
output in question has:
Address unlock condition => wallet 1 address
Same Expiration UC=> rms1qzezp3th8yrsrukh8jtlme4v23zqdm94hmrxf4dnj05exltt0jm75xc753j (sender address)

Why can we fetch output data for second transaction but not for first. Its basically the same output and only difference is the Sender, Metadata and Alias address in AddressUnlockCondition. 

some more tx that we are unable to get the output details for;

- https://explorer.shimmer.network/testnet/transaction/0xcb227fdb92e70b9186dae7cbc9fcabcd7c13a48c1fb4ae2a9e4a48a999c2d91f
- https://explorer.shimmer.network/testnet/transaction/0xdb439dc38c5a24c2b85683d98d0c3ebad1cfaaeea35999e2571eb067d1a86095

As a result some transactions are marked as unclaimed in FireFly
![image](https://github.com/iotaledger/iota-sdk/assets/52735957/c1bc4806-0288-4b5f-94c2-7930e74283e6)

### Version

sdk 1.1.1

### Expected behaviour

Able to fetch output details

### Actual behaviour

unable to fetch output details

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Did you sync the wallet after the transaction was included and before you called `account.getOutput(outputId)`?
The output is only available after the transaction is included and the account is then synced

**Comment by Thoralf-M** [comment]
@brancoder I wasn't able to reproduce it with nodejs scripts, can you provide steps how to reproduce it with the sdk alone?

**Comment by brancoder** [comment]
> @brancoder I wasn't able to reproduce it with nodejs scripts, can you provide steps how to reproduce it with the sdk alone?

@Thoralf-M I cant provide the steps because I wasnt able to figure out why this happens. I will check again and try to pinpoint what causes the issue or at least how to reproduce it.

**Comment by thibault-martinez** [comment]
Hi @brancoder, did you find a way to reproduce this?

**Comment by brancoder** [comment]
@thibault-martinez @Thoralf-M  I haven't been able to reliably reproduce it. We can close the issue and ill reopen it if needed.
