### ISSUE TITLE
Remove address from OutputData struct

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1514]
## Description

Remove address from OutputData struct, since it doesn't really make sense there if we only have a single address in the wallet. In stardust it was used so the address with the output got added to the addresses_with_unspent_outputs

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1604
