### ISSUE TITLE
Re-evaluate places where we are taking locks across await points

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#1543]
## Description

We need to evaluate the places where we are calling Wallet::data and data_mut and holding the lock across await points

## Motivation

Possible risk of dead locks.

**Comment by thibault-martinez** [comment]
For reference, this is very much already happening https://github.com/iotaledger/iota-sdk/pull/1510

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1812
