### ISSUE TITLE
Ensure test coverage of #1557

### ISSUE THREAD

**Issue by tadzik** [iotaledger/iota-sdk#1558]
## Description

https://github.com/iotaledger/iota-sdk/pull/1557 was submitted at the time of Python bindings being broken for 2.0, making its testing tricky. It should be revisited once the bindings (and the tests) work again.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by Thoralf-M** [comment]
It's tested in https://github.com/iotaledger/iota-sdk/blob/0ac4ff46671966c83296e329b284f422d434af19/bindings/python/tests/test_output.py#L29 now https://github.com/iotaledger/iota-sdk/blob/0ac4ff46671966c83296e329b284f422d434af19/bindings/python/tests/test_output.py#L183-L185
