### ISSUE TITLE
Have semantic_validation() for tx essence/payload without unlocks

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1570]
## Description

Have semantic_validation() for tx essence/payload with the unlocks optional. And make it available to the bindings.

## Motivation

Currently semantic_validation() accepts the signed transaction, but it would also make sense to have an option to validate the tx before signing, so one doesn't have to resign if something is wrong.

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
We can't change that on develop though?

**Comment by Thoralf-M** [comment]
Why not? We can keep the existing one and add a new method?

Edit: we decided to not do it on develop, because without breaking change it would require a lot duplication (like ~15 functions and the ValidationContext)

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1572
