### ISSUE TITLE
Reconsider what Address Display should be

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1587]
It just forwards to the display impls of the rest of the addresses. We Display only the hex IDs for the addresses. We may want to reconsider what we want as Display but not in this PR I'd say.

_Originally posted by @thibault-martinez in https://github.com/iotaledger/iota-sdk/pull/1573#discussion_r1384874421_

**Comment by kwek20** [comment]
So the  display of addresses currently looks like this:
Ed25519(hex-encoded-hash) 
Account(AccountId(hex-encoded-hash))
Nft(NftId(hex-encoded-hash))
Anchor(AnchorId(hex-encoded-hash))
ImplicitAccountCreation(Ed25519(hex-encoded-hash) )
Multi([
  Address(*),
  weight
]) -> missing threshold at multi
Restricted(hex-encoded(address+capabilities))

Id propose we completely change multi to the hash(`Let Address Hash be the BLAKE2b-256 hash of the serialized Multi Address.`), as the others have (my favourite)

No type/kind in display, debug has the name prepended already if thats needed

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1790
