### ISSUE TITLE
CLI: Ask the user whether to write the generated mnemonic into a plain-text file

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#160]
## Description

The title says it all.

## Motivation

Some users may not want that the generated mnemonic gets written to a plain-text file, which might become a security risk since not all users are able to safely delete files permanently in a way that is not recoverable.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by DaughterOfMars** [comment]
What do you expect the alternative to be? The subcommand creates the file and exits, so in order to avoid that you would simply not use the command.

**Comment by Alex6323** [comment]
The alternative would be to just print it to the console so that the user can write it down on a piece of paper or store it somewhere else like in an encrypted password manager.

**Comment by Alex6323** [comment]
here is an example implementation:
https://github.com/Alex6323/iota-sdk/blob/feat/cli/refactor-cli-wallet/cli-wallet/src/cli/commands/mnemonic.rs
