### ISSUE TITLE
[Bug]: Chronicle node issue?

### ISSUE THREAD

**Issue by T-Martin-Ulster** [iotaledger/iota-sdk#1614]
### Issue description

I have a rust script (see below), it gets the data from a tagged data payload using a BlockId.

use iota_sdk::{client::{Client, Result}, types::block::payload::{Payload},};

#[tokio::main]
async fn main() -> Result<()> {
 
    // Take the node URL from command line argument.
    let node_url = std::env::args()
        .nth(1).unwrap();

    // Create a node client.
    let client = Client::builder().with_node(&node_url)?.finish().await?;

    // Take the block ID from command line argument or...
    let block_id = if let Some(Ok(block_id)) = std::env::args().nth(2).map(|s| s.parse()) {
        block_id
    } else {
        // ... fetch one from the node.
        client.get_tips().await?[0]
    };

    // Get the block.
    let block = client.get_block(&block_id).await?;

    let payload = block.payload().unwrap();

    if let Payload::TaggedData(tagged_data_payload) = payload {

        let bytes = tagged_data_payload.data();

        let string = String::from_utf8(bytes.to_vec()).expect("Found invalid UTF-8");

        println!("{string:#?}");
    }

    Ok(())
}

The script works perfectly when used on a Hornet node, but returns "Error: HealthyNodePoolEmpty" when used on a Chronicle node.

The Chronicle node is healthy and I can get the data by calling the endpoint directly using postman. The Chronicle node uses the same api endpoints as a hornet node so unless I'm missing something it should work.

### Version

Latest

### Expected behaviour

The script should return the data stored inside a tagged data payload.

### Actual behaviour

The script returns: "Error: HealthyNodePoolEmpty"

### Can the issue reliably be reproduced?

Yes

### Errors

Error: HealthyNodePoolEmpty

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Can you show the info response you get from chronicle? If I remember correct it wasn't compatible because some field was not correct

**Comment by T-Martin-Ulster** [comment]
Chronicle api info response:

"name": "Chronicle",
    "version": "1.0.0-rc.2",
    "status": {
        "isHealthy": true,
        "latestMilestone": {
            "index": 1735,
            "timestamp": 1699906120,
            "milestoneId": "0x4fd8c6535468acea865fc5114928651844649d0c0874508db256c7e50cc7b900"
        },
        "confirmedMilestone": {
            "index": 1735,
            "timestamp": 1699906120,
            "milestoneId": "0x4fd8c6535468acea865fc5114928651844649d0c0874508db256c7e50cc7b900"
        },
        "pruningIndex": 0
    },
    "protocol": {
        "version": 2,
        "networkName": "private_tangle1",
        "bech32Hrp": "tst",
        "minPowScore": 0,
        "belowMaxDepth": 15,
        "rentStructure": {
            "vByteCost": 500,
            "vByteFactorKey": 10,
            "vByteFactorData": 1
        },
        "tokenSupply": "2779530283277761"
    },
    "baseToken": {
        "name": "TestCoin",
        "tickerSymbol": "TEST",
        "unit": "TEST",
        "subunit": "testies",
        "decimals": 6,
        "useMetricPrefix": false
    }
}

**Comment by T-Martin-Ulster** [comment]
I bad at this

**Comment by Thoralf-M** [comment]
@T-Martin-Ulster this is the error I get `Error("missing field `supportedProtocolVersions`", line: 38, column: 1)`
So this is actually a chronicle bug, it's missing a required field in the response
https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/main/tips/TIP-0025/core-rest-api.yaml
```
      required:
        - name
        - version
        - status
        - metrics
        - supportedProtocolVersions
```

**Comment by Thoralf-M** [comment]
Opened an issue in the chronicle repo

**Comment by DaughterOfMars** [comment]
Not a bug, this was implemented differently because chronicle is not a node.

**Comment by T-Martin-Ulster** [comment]
So its a compatibility issue, the IOTA sdk uses the /info endpoint to check the health of the node, but because chronicle isn't a true node it returns less fields resulting in the sdk thinking the node is unhealthy.

**Comment by DaughterOfMars** [comment]
Try using `ClientBuilder::with_permanode` instead:

```
let client = Client::builder().with_permanode(&node_url)?.finish().await?;
```

**Comment by T-Martin-Ulster** [comment]
@DaughterOfMars Yep that works, with_permanode requires an additional argument but it has solved my issue. Thanks.

let node_auth = iota_sdk::client::node_manager::node::NodeAuth {
        jwt: Some(jwt),
        basic_auth_name_pwd: None,
    };

    // Create a node client.
    let client = Client::builder().with_permanode(&node_url, Some(node_auth) )?.finish().await?;
