### ISSUE TITLE
Keep permanode support as it is?

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1620]
Do we want permanode support in the client like it is now or should we change/remove it? Currently it's a bit messy, one can add a permanode with `with_permanode()` and in `get_request()` have a `prefer_permanode` bool parameter we hardcoded for each endpoint, which will then use a permanode first if available and otherwise a normal node.
Nodeinfo doesn't work because the response is different, posting a block and getting tips will never be possible, but for users it's not clear what is supported or not.
Permanodes also have other API endpoints one can call with `call_plugin_route()`, but currently only if one would provide a permanode as normal node, because there `prefer_permanode` is set to false

**Comment by Alex6323** [comment]
Sounds like this just needs some cleanup tbh. I think permanode support is quite valuable for particular routes so I would keep it. We should however find a good way to tell the user what is supported by the permanode and what not.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1980
