### ISSUE TITLE
Update MQTT topics for 2.0

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1636]
https://github.com/iotaledger/iota-sdk/blob/7bf364d4f91f0b41bc5a2decc7a6b6f5fcc47617/sdk/src/client/node_api/mqtt/types.rs#L170-L188
needs to be updated to
https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/iotaledger/tips/tip48/tips/TIP-0048/asyncapi3.yaml

And examples shouldn't use `milestone-info/latest`, but `commitment-info/latest` instead

Can be tested with `http://localhost:8050`  in `07_mqtt.rs` and with https://github.com/iotaledger/iota-core/blob/develop/tools/docker-network/run.sh

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1785
