### ISSUE TITLE
Update OutputMetadata

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1639]
## Description

Update OutputMetadata to https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/tip48/tips/TIP-0048/openapi3-core.yaml
In bindings

## Motivation

It's outdated

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1685
