### ISSUE TITLE
Add RouteBlockWithMetadata = "/blocks/:" + restapipkg.ParameterBlockID + "/full"

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1649]
Add new route which returns a block together with its metadata
https://github.com/iotaledger/tips/pull/153/files/107c6f5397d218740fbe639c1b11df8e6eae4066..0e1dd9ac0a0ef3ec891ed5a3ebf8f9e5602e7f1b
Also update bindings

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1707
