### ISSUE TITLE
Remove duplicate CI workflows for bindings

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/iota-sdk#165]
## Description

We have some duplicate workflows and jobs. For example, the `nodejs-bindings` job in [`build-and-test.yml`](https://github.com/iotaledger/iota-sdk/blob/develop/.github/workflows/build-and-test.yml) is very similar to the `test` job in [`bindings-nodejs.yml`](https://github.com/iotaledger/iota-sdk/blob/develop/.github/workflows/bindings-nodejs.yml). This results in potentially unnecessary jobs and contributes more to the organization-wide concurrency limit.

## Motivation

- Prevent unnecessary jobs
- Avoid longer queue times in this repo and other `iotaledger` repos

## Bindings
- [ ] Node.js
- [ ] Java
- [ ] Swift
- [ ] WASM
- [ ] Python

## Are you planning to do it yourself in a pull request?

Yes

**Comment by thibault-martinez** [comment]
Yeah this is a remnant from the repositories merge that we still haven't had time to clean up. If you so, I think I'd prefer to keep the individual bindings files.

**Comment by rajivshah3** [comment]
> If you so, I think I'd prefer to keep the individual bindings files.

Yep, I think that's probably best since we can then ignore paths that aren't relevant (we don't need to build Node.js bindings when Python files are changed, for example)

**Comment by Thoralf-M** [comment]
Move 
https://github.com/iotaledger/iota-sdk/blob/76ef5679baf5029b0c01f17de4baabefdcbd4081/.github/workflows/build-and-test.yml#L104-L447 (wallet bindings) into their own workflows files like
workflows/wallet-bindings-java.yml
workflows/wallet-bindings-nodejs.yml
workflows/wallet-bindings-python.yml
... as we have for the client bindings currently, for example https://github.com/iotaledger/iota-sdk/blob/develop/.github/workflows/bindings-nodejs.yml

Only run it when relevant, so like here https://github.com/iotaledger/iota-sdk/blob/76ef5679baf5029b0c01f17de4baabefdcbd4081/.github/workflows/bindings-nodejs.yml#L6-L15 just with wallet

Bindings will be merged soon, so I guess it's no problem to have two workflow files for each language now (not sure if they can be merged into a single one while still only run when relevant (client when something in client binding changes, wallet when something in wallet binding changes)

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/265
