### ISSUE TITLE
Add StateMetadataFeature

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1650]
https://github.com/iotaledger/tips/blob/tip54/tips/TIP-0054/tip-0054.md#state-metadata-feature

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1849

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/iota-sdk/blob/24531a8dd0fe4a4dcfc6f5e6a1d01855a2213dd0/sdk/src/types/block/output/anchor.rs#L477

**Comment by Thoralf-M** [comment]
Bindings need to be updated

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2030
