### ISSUE TITLE
Add more PublicKey generation fallbacks

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1666]
- [x] https://github.com/iotaledger/iota-sdk/pull/1598/files#diff-bb97bc42ed78814b7c87abe4a31292fcfa12055d3bf69e2dd7ed05666178fbb0R51

**Comment by Thoralf-M** [comment]
Probably should also have a parameter where it can be provided as Option

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1702
