### ISSUE TITLE
Check if more dtos can be made private/removed

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1713]
https://github.com/iotaledger/iota-sdk/pull/1712 makes the output dtos private and structs like `InputSigningData`, `RemainderDataDto` had a dto just because of the OutputDto, so `InputSigningDataDto` and maybe others can now also be removed/made private.

**Comment by thibault-martinez** [comment]
Also `OutputDataDto`?

**Comment by Thoralf-M** [comment]
`UnlockConditionDto`

**Comment by thibault-martinez** [comment]
Remove `try_from_dtos`s ?

**Comment by thibault-martinez** [comment]
`PayloadDto` ?

**Comment by Thoralf-M** [comment]
AccountOutputDto, BasicOutputDto... can be private and removed if we find a better solution for the type field

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1817
