### ISSUE TITLE
Merge TransactionOptions into a new BlockOptions?

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1740]
Need IssuerId as BlockOptions, do we need more than that? We currently pass that + TransactionOptions in most APIs now.

- [ ] Maybe add issuance to it to avoid having to call it twice ? (https://github.com/iotaledger/iota-sdk/pull/1739/files#diff-bb97bc42ed78814b7c87abe4a31292fcfa12055d3bf69e2dd7ed05666178fbb0R102)

**Comment by Alex6323** [comment]
Have the alternatives already been discussed? Pretty much settled on the `BlockOptions` wrapper, or still open to just renaming `TransactionOptions` to `BlockOptions` with additional fields?

**Comment by thibault-martinez** [comment]
There is only one issuance call anymore, no need to do this.
