### ISSUE TITLE
Remove all secret manager methods from the wallet?

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1765]
## Description

Like store_mnemonic(), get_ledger_nano_status(), change_stronghold_password()...

## Motivation

Can be called from the secret manager instead and not fail if another secret manager is used

## Are you planning to do it yourself in a pull request?

No.

**Comment by Alex6323** [comment]
I would remove those methods you mentioned because those will clearly only work with one specific secret manager. But we should keep those - if any - that can work with multiple.

**Comment by Alex6323** [comment]
Decided to keep those methods for now.
