### ISSUE TITLE
Fix block id computation

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1781]
Currently for some reason node returns "0x00c62140075ce5ecb1aa85d3a24f9807a41ccd4599b70c81f3905c9a067f2410575a0000", but we return
"0x00c62140075ce5ecb1aa85d3a24f9807a41ccd4599b70c81f3905c9a067f2410525a0000", so `7` is replaced by `2` for some reason

```TS
        let info = await client.getInfo();
        const block = await client.getBlock("0x00c62140075ce5ecb1aa85d3a24f9807a41ccd4599b70c81f3905c9a067f2410575a0000");
        console.log(Utils.blockId(block, info.nodeInfo.protocolParameters[0].parameters))
```

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1782
