### ISSUE TITLE
[Bug]: network ID mismatch without healthy node

### ISSUE THREAD

**Issue by msarcev** [iotaledger/iota-sdk#1808]
### Issue description

`getIncludedBlock` returns error response on mainnet Chronicle.

Can be reproduced with this example:
```
// Copyright 2021-2023 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

import { Client, initLogger } from '@iota/sdk';
require('dotenv').config({ path: '.env' });

// Run with command:
// yarn run-example ./how_tos/client/get-outputs.ts

// In this example we will get the outputs of a known address
async function run() {
    initLogger();
    for (const envVar of ['NODE_URL']) {
        if (!(envVar in process.env)) {
            throw new Error(`.env ${envVar} is undefined, see .env.example`);
        }
    }

    const client = new Client({
        // Insert your node URL in the .env.
        nodes: [process.env.NODE_URL as string],
        ignoreNodeHealth: true
    });

    try {
        // Get output ids of basic outputs that can be controlled by this address without further unlock constraints
        const theBlock = await client.getIncludedBlock("0x325d2ecd348108dc930a4e11679f0bd949ca48200d5964f3169a8773131ffc17");
        console.log(theBlock);
    } catch (error) {
        console.error('Error: ', error);
    }
}

run().then(() => process.exit());
```

NODE_URL: `https://chronicle.stardust-mainnet.iotaledger.net`

### Version

develop (stardust)

### Expected behaviour

The Block should be found, as it works when using the API directly

### Actual behaviour

Network ID mismatch error is returned

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Use the `getIncludedBlock` client function with TX id `0x325d2ecd348108dc930a4e11679f0bd949ca48200d5964f3169a8773131ffc17`

### Errors

```{"type":"error","payload":{"type":"client","error":"network ID mismatch: expected 14364762045254553490 but got 9374574019616453254"}}```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/iota-sdk/blob/2b44b886538b3c5dbbaf55a8ace38e8f44273bfe/sdk/src/client/node_api/core/routes.rs#L306-L309
could just be replaced with `Ok(Block::try_from_dto(dto)?)`, but if we want that behavior we probably want to replace all `try_from_dto_with_params()` usages in routes.rs

Alternative would be to say this is expected and users have to provide the correct protocol parameters

**Comment by Thoralf-M** [comment]
@msarcev if you build the client with chronicle and a hornet node endpoint like `"https://api.stardust-mainnet.iotaledger.net"` it works, alternatively you can provide the protocol parameters directly without another node like this
```TS

import { Client } from '@iota/sdk';

async function run() {

    const protocolParameters = {
        "version": 2,
        "networkName": "iota-mainnet",
        "bech32Hrp": "iota",
        "minPowScore": 1500,
        "belowMaxDepth": 15,
        "rentStructure": {
            "vByteCost": 250,
            "vByteFactorData": 1,
            "vByteFactorKey": 10
        },
        "tokenSupply": "4600000000000000"
    };

    const client = new Client({
        permanodes: ["https://chronicle.stardust-mainnet.iotaledger.net"],
        ignoreNodeHealth: true,
        // @ts-ignore
        protocolParameters,
    });

    try {
        const theBlock = await client.getIncludedBlock("0x325d2ecd348108dc930a4e11679f0bd949ca48200d5964f3169a8773131ffc17");
        console.log(theBlock);
    } catch (error) {
        console.error('Error: ', error);
    }
}

run().then(() => process.exit());
```

**Comment by Thoralf-M** [comment]
@msarcev can this issue be closed?

**Comment by begonaalvarezd** [comment]
We fixed it in the explorer https://github.com/iotaledger/explorer/pull/984

**Comment by Thoralf-M** [comment]
We now changed the way permanodes are handled https://github.com/iotaledger/iota-sdk/pull/1980
Recommended way is to set a hornet node first and then the permanode, this way hornet will handle all the requests and only if it fails the permanode will be tried
