### ISSUE TITLE
Use decayed potential mana in ISA

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1823]
Currently just sums the mana amount of the outputs https://github.com/iotaledger/iota-sdk/blob/69570c74632f367d051ca46567f862c5a4066f73/sdk/src/client/api/block_builder/input_selection/requirement/mana.rs#L10

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1847
