### ISSUE TITLE
Update OutputMetadata in Python

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1825]
Update https://github.com/iotaledger/iota-sdk/blob/91e0a80fd11dc65687dc3347b3515dbf486130cb/bindings/python/iota_sdk/types/output_metadata.py#L14 to https://github.com/iotaledger/iota-sdk/blob/91e0a80fd11dc65687dc3347b3515dbf486130cb/sdk/src/types/block/output/metadata.rs#L94 since it's outdated

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1860
