### ISSUE TITLE
[Bug]: `blockIssuerKeys` array not included in response (nodejs)

### ISSUE THREAD

**Issue by msarcev** [iotaledger/iota-sdk#1835]
### Issue description

The `BlockIssuerFeature` doesn't seam to be honoured in the API response. Found the issue fetching this output through Explorer `0xa7e1df38221310d3a108128772cb66e146cecf3c90b6247b5f7e943cd89634ec290100000000`

Additionally i wanted to reproduce the issue using `/bindings/nodejs/examples/client/04-get-output.ts` example, but that one throws an error for me when ran:
`Error:  TypeError: failed to downcast any to string`
Maybe it indicated a different issue.

### Version

2.0

### Expected behaviour

The json response should include all the field as when fetched from the node API
```
{"output":{"type":1,"amount":"1000000000","mana":"168841","accountId":"0x74b29e0cbb1eff9fd192760de13d6bdf596a2bf491822e0be5f73724e754d67f","foundryCounter":0,"unlockConditions":[{"type":0,"address":{"type":0,"pubKeyHash":"0xf6ebdfdb209513d15b6f1bd9c3f50a40ff5f28f9cd317f8bb9f8e0bd21ba172d"}}],"features":[{"type":6,"expirySlot":4294967295,"blockIssuerKeys":[{"type":0,"publicKey":"0x2b1472cf4e89fa4cfc009649b24ae318eb3d3b4bfab97a4bc9c8c73d526cb507"}]}]},"outputIdProof":{"slot":297,"outputIndex":0,"transactionCommitment":"0xfc734d48ccd4cb67874a1f96d8e9f7221133afa4f923ff300b03574c05acc609","outputCommitmentProof":{"type":2,"hash":"0xf13f6bc719c7a0676ae2762f31918e1f5a4862d837bf4459969ac88868be10b3"}}}
```

### Actual behaviour

The json i get when fetching with the SDK (same output)
```
 {"metadata":{"outputId":"0xa7e1df38221310d3a108128772cb66e146cecf3c90b6247b5f7e943cd89634ec290100000000","blockId":"0x4aa41cc41892855a31225f6f7e1a7ae984131126c0e95316b212a5be40769bdc29010000","included":{"slot":297,"transactionId":"0xa7e1df38221310d3a108128772cb66e146cecf3c90b6247b5f7e943cd89634ec29010000","commitmentId":"0xd412b86bc7706b3ce2d6dcd50338fe3e76bc2b4b2e695f828dc122e61971eb2729010000"},"latestCommitmentId":"0x5481f61f500c494f56b3260251fd5030ecc5079974099ebb5d46fe0996e02c4bf1010000"},"output":{"type":1,"amount":"1000000000","unlockConditions":[{"type":0,"address":{"type":0,"pubKeyHash":"0xf6ebdfdb209513d15b6f1bd9c3f50a40ff5f28f9cd317f8bb9f8e0bd21ba172d"}}],"accountId":"0x74b29e0cbb1eff9fd192760de13d6bdf596a2bf491822e0be5f73724e754d67f","foundryCounter":0,"mana":"168841","features":[{"type":6,"expirySlot":4294967295,"blockIssuerKeys":{}}]}}
```

Notice the `blockIssuerKeys: {}`

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Use the SDK to fetch the account output above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1836
