### ISSUE TITLE
[Bug]: mismatch between Nodejs `bigint` types and (hex) `string` types

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/iota-sdk#1839]
### Issue description

In the bindings, several interfaces are typed as BigInts, but expect or return hex encoded strings. This should be improved. Examples:
- TokenScheme: https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/lib/types/block/output/token-scheme.ts#L39-L42
- CreateNativeTokenParams: https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/lib/types/wallet/transaction-options.ts#L70
- There might be others. I haven't performed an exhaustive search

### Version

1.1.4

### Expected behaviour

Correct typings: if hex encoded amounts are returned then they should be typed as `HexEncodedAmount`, if it is of Javascript BigInt types, then they should be typed as `bigint`. Refrain from returning numbers, as that will result in lost precision.

### Actual behaviour

Incorrect typings for bigints. They return hexadecimal strings

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create a new TokenScheme with circulating and total supply of `1000000000000000000000000000000n` BigInt type
2. Will result in a total supply of 1329227995784915872903807060280344576n, because it is being interpreted as a hex string

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
What exactly do you do? I just tried https://wiki.iota.org/iota-sdk/how-tos/native-tokens/create/?language=typescript-node with BigInt("1000000000000000000000000000000") and for me this works as expected https://explorer.shimmer.network/testnet/output/0x631cd499cf03905fdcee363b467446d7e5df672ccf3b51f979c64fb9af7838ce0100

**Comment by Tuditi** [comment]
Good question, I tried reproducing this to no avail, so maybe the problem was on our side. I'll close it for now and reopen it if I encounter it again.

**Comment by Tuditi** [comment]
I found the reproduction steps. There are two issues I found (there might be more).

1. When minting a native token, the prepared `FoundryOutput` contains the tokenscheme as a hex encoded string. This is mismatched in https://github.com/iotaledger/iota-sdk/blob/2b44b886538b3c5dbbaf55a8ace38e8f44273bfe/bindings/nodejs/lib/types/block/output/token-scheme.ts#L39-L42

Add the following lines [after `account.prepareCreateNativeToken(params);` ](https://github.com/iotaledger/iota-sdk/blob/2b44b886538b3c5dbbaf55a8ace38e8f44273bfe/bindings/nodejs/examples/how_tos/native_tokens/create.ts#L72)

```
@ts-expect-error output only exists on Foundry Output
console.log('prepared', prepared._preparedData.essence.outputs)
```

2. When getting the native token amounts from a basic output presents the same issue. You can investigate your outputs with native tokens using the list-output.ts example and replacing l.32 with

`for (const output of outputs) console.log(output.output);`
