### ISSUE TITLE
Add `BLOCK_FAILURE_REASON_STRINGS`

### ISSUE THREAD

**Issue by brancoder** [iotaledger/iota-sdk#1846]
## Description

Add `BLOCK_FAILURE_REASON_STRINGS` for blocks similar to  `TRANSACTION_FAILURE_REASON_STRINGS` for transactions.

## Requirements

Write a list of what you want this feature to do.

1. 
2. 
3. 

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1859
