### ISSUE TITLE
[Bug]: The requested data [api.testnet.shimmer.network] was not found [NFT]

### ISSUE THREAD

**Issue by drtwodog** [iotaledger/iota-sdk#1850]
### Issue description

Hello,

I did some testing inside of the [api.testnet.shimmer.network].
There I had a strange behavior:
A NFT: 0xcf4b6b9ba150cd800ae56b4974530734929afdd2eebe99a56fc966b25ca40eb5 that was created (17.01.2024) is not available anymore: {"type":"error","payload":{"type":"client","error":"node error: The requested data https://api.testnet.shimmer.network/api/indexer/v1/outputs/nft/0xcf4b6b9ba150cd800ae56b4974530734929afdd2eebe99a56fc966b25ca40eb5 was not found."}}

A NFT:0x8d591055ce2a62d44a02e451f9186959a81bfa1088519f3da2160398b660b7e2 that was created one day before (16.01.2024) is available.

-> Both NFTs were "accessable" (->Could be displayed) on the 17.01.2024 

What could that be?

### Version

nodejs - @iota/sdk": "1.1.4

### Expected behaviour

Should be visible

### Actual behaviour

Not visible 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create NFT
2. Wait 
3. 

### Errors

{"type":"error","payload":{"type":"client","error":"node error: The requested data https://api.testnet.shimmer.network/api/indexer/v1/outputs/nft/0xcf4b6b9ba150cd800ae56b4974530734929afdd2eebe99a56fc966b25ca40eb5 was not found."}}

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
How did you get this NFT ID 0xcf4b6b9ba150cd800ae56b4974530734929afdd2eebe99a56fc966b25ca40eb5?

**Comment by drtwodog** [comment]
Via Account Address: rms1qrdze3gtqk6l2lx32j8e0qkgrgrp2e4m5ht4a5s7z7vlsllkv0j6cvpeqc3

Output Creation:
        const output :NftOutput= await onlineClient.buildNftOutput({
            
            nftId: '0x0000000000000000000000000000000000000000000000000000000000000000',
            unlockConditions: [
                new AddressUnlockCondition(
                    new Ed25519Address(Utils.bech32ToHex(NFT_OWNER_ADDRESS)),
                ),
            ],
            immutableFeatures: [
                new IssuerFeature(new Ed25519Address(hexAddress)),
                new MetadataFeature(utf8ToHex(JSON.stringify(_irc27))),
            ],
            features: [
                new SenderFeature(new Ed25519Address(hexAddress)),
                new TagFeature(utf8ToHex(tag.toString()))
                
            ],
        });

...
var transaction = await account.sendOutputs([output]);

Remark: I see the NFT -> There is no expiry defined...therefore this is a little bit strange...

**Comment by Thoralf-M** [comment]
You just showed how to send an NFT output, but not any code how you got the NFT ID.

> Remark: I see the NFT -> There is no expiry defined...therefore this is a little bit strange...

Where do you see it? No expiration unlock condition makes sense if you only provide an address unlock condition

**Comment by drtwodog** [comment]
-> Ahhh ok ...
I test with your examples and created with stronghold my account -> There I see that the NFT is assigned to my account (I list my NFTs to my account), but if I got to the tangle-explorer, or try to get the data from the tangle it says that it is not there.

Yesterday, when I created that NFT I saw the Metadata at the tangle -> (tangle Explorer)

**Comment by Thoralf-M** [comment]
If you have the NFT output locally, can you send its metadata?

**Comment by drtwodog** [comment]
Hey -> Here it is... I see that a different nftid is entered in the output  (this is available within the explorer) ... why is there a difference?
(Below is a output with a nft 0x000... -> This is nftid from the account is accessable within the explorer..)
-> Could you explain that behavior?

{
  nftID: '0xcf4b6b9ba150cd800ae56b4974530734929afdd2eebe99a56fc966b25ca40eb5',
  nftOutput: OutputResponse {
    metadata: {
      blockId: '0xe3aadf755447d02fbb432592440071295056d4496e2193d3c88196223969ffcd',
      transactionId: '0x0afe6a87c6875eee4ff55196976480b717dcdffaf5863b4143a8494fbb679b10',
      outputIndex: 1,
      isSpent: false,
      milestoneIndexBooked: 1534862,
      milestoneTimestampBooked: 1705511325,
      ledgerIndex: 1546390
    },
    output: NftOutput {
      type: 6,
      amount: '366800',
      unlockConditions: [Array],
      nftId: '0xff09d385818f79ad408d4caf0c5a33a90a09b6955e2725adf921ef00bd8a4451',
      features: [Array],
      immutableFeatures: [Array]
    }
  }
}


{
  nftID: '0x3988ac0ce7e232d119566b5dd57c0caa5fe2bced16b2487daf6cd9a92a0427ef',
  nftOutput: OutputResponse {
    metadata: {
      blockId: '0xb87269a82c3e042b2a650745ef5729a8f7b01109e7ca5cae2d66b74f6cde56ca',
      transactionId: '0x3be94aaec0603816d922d55c6e106df3d42912b8349fef090596abc57074333d',
      outputIndex: 0,
      isSpent: false,
      milestoneIndexBooked: 1542496,
      milestoneTimestampBooked: 1705550441,
      ledgerIndex: 1546390
    },
    output: NftOutput {
      type: 6,
      amount: '267900',
      unlockConditions: [Array],
      nftId: '0x0000000000000000000000000000000000000000000000000000000000000000',
      features: [Array],
      immutableFeatures: [Array]
    }
  }
}

**Comment by drtwodog** [comment]
...ahhh...maby I understand ... that what I understood as nftId are the nftOutputIds...and not the nftids (my bad...)...???

But in cases of the nftId: '0x0000000000000000000000000000000000000000000000000000000000000000 in the output... how to get the correct nftid?

**Comment by Thoralf-M** [comment]
```
{
nftID: '0xcf4b6b9ba150cd800ae56b4974530734929afdd2eebe99a56fc966b25ca40eb5',
nftOutput: OutputResponse {
metadata: {
blockId: '0xe3aadf755447d02fbb432592440071295056d4496e2193d3c88196223969ffcd',
transactionId: '0x0afe6a87c6875eee4ff55196976480b717dcdffaf5863b4143a8494fbb679b10',
outputIndex: 1,
isSpent: false,
milestoneIndexBooked: 1534862,
milestoneTimestampBooked: 1705511325,
ledgerIndex: 1546390
},
output: NftOutput {
type: 6,
amount: '366800',
unlockConditions: [Array],
nftId: '0xff09d385818f79ad408d4caf0c5a33a90a09b6955e2725adf921ef00bd8a4451',
features: [Array],
immutableFeatures: [Array]
}
}
}
```
`0xcf4b6b9ba150cd800ae56b4974530734929afdd2eebe99a56fc966b25ca40eb5` is wrong here because it's the hash of the output id even though the output is not newly minted here (NFT ID not 0x000...)

> But in cases of the nftId: '0x0000000000000000000000000000000000000000000000000000000000000000 in the output... how to get the correct nftid?

Only in this case the hash of the output id will result in the nft id, if the nft id is set, then one has to use it from the output itself and not compute it again

**Comment by drtwodog** [comment]
Ok I´m close to understand it :-)

in cases of nftid "0x000" the hash of the output Id = the nftid (see attachement 
![2024-01-18 10_48_30-Testnet Explorer](https://github.com/iotaledger/iota-sdk/assets/143087512/1f62cbca-31fb-4179-a76e-b0fc5ffd30e3)
)

Why and how to update the nftid? -> Utils.computeOutputId   / Utils.computeNftId(outputId);   -> ?
-> I think that **why** i more important...

**Comment by Thoralf-M** [comment]
> Why update the NFT ID? 

This is done during the first time the NFT is transitioned so the actual NFT ID is in the output itself (it can't be set while minting it since the hash of the tx in which it gets minted is needed) https://github.com/iotaledger/tips/blob/main/tips/TIP-0018/tip-0018.md#additional-transaction-semantic-validation-rules-3
So if you send the NFT output, on the output side you have to set its NFT ID, otherwise you will just mint a new one

**Comment by drtwodog** [comment]
Hey Thoralf -> I didn`t thank you for your great support so far -> Big thanx!!!

ok... after a few tests I hopefully understand the topic.
-> I want to have an identical number -> the NFTID - It should be unique even if I send it...
-> Now my question is: How can i set the explicit nftID after minting it (in my account)? Is there a function?

MySteps:
I mint a NFT using the buildNftOutput  -> It creates the implicit NFT ID (=Output id) an the nftId in the output = 0x0.
-> Now I want to set the explicit NFTID (**How**?) - after the minting the Utils.computeNftId delivers the implicit number!
How is it possiblie to set the explicit NFT ID?

**Comment by Thoralf-M** [comment]
> I want to have an identical number -> the NFTID - It should be unique even if I send it...

Since the NFT ID depends on the output id its guaranteed to be unique. If you try to set the same NFT ID for another NFT output, it will result in a conflicting transaction.

> How can i set the explicit nftID after minting it (in my account)? Is there a function?

You can build the NFT output with the correct ID and send it to yourself, or just use https://wiki.iota.org/iota-sdk/how-tos/nfts/send-nft and send it to yourself. But it's not needed to manually explicitly set it, if you just send the NFT with the ID somewhere the SDK will automatically set it.

**Comment by drtwodog** [comment]
got it-> A Big thx again for your patience and the great Support
