### ISSUE TITLE
[Bug]: Prevent sending Output to NFT?

### ISSUE THREAD

**Issue by drtwodog** [iotaledger/iota-sdk#1851]
### Issue description

Hello,

Maybe not an Bug.
In my account I have a NFT. 
 - According to that NFT I store additional Data to that NFT via Outputs

How can I prevent that a other user can add outputs to that NFT.

-> I tested it that an other account could send outputs to that NFT

Regards,

### Version

1.1.4

### Expected behaviour

Maybe there is a prevent switch?

### Actual behaviour

Not known user could send outputs to my NFT and add some data

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
> How can I prevent that a other user can add outputs to that NFT

If you mean just create an output with the NFT address in the unlock condition, then this is not possible to prevent.
You could add a sender feature to your outputs and filter them by that, this way you can make sure that the outputs are only from you

**Comment by drtwodog** [comment]
I thought about that... but that means that anyone could send data to my nft without my permission. (Of course, everybody could send some tokens / money to me.... 
ok that filtering thing is good an then remove the rest...
