### ISSUE TITLE
Remove auto reissue transaction

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/iota-sdk#1867]
## Description

Should we remove the auto reissue for transactions during syncing, since they require additional mana?

## Motivation

https://github.com/iotaledger/iota-sdk/pull/1756#discussion_r1461875596
> I guess we shouldn't do this automatically for now (or never), since it also requires more mana which doesn't get allotted if we just submit the same payload

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1897
