### ISSUE TITLE
Should `ProtocolParameters` impl `Default`?

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#1876]
## Description

We should think about whether that really makes sense considering:
* values change over time through fluid protocol upgrades (what happens then? Updating the defaults?)
* there are several networks in parallel (not clear why defaulting to a particular one of those?)
* buggy as shown with https://github.com/iotaledger/iota-sdk/issues/1808

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1969
