### ISSUE TITLE
Add TIP API response tests to Python and Nodejs

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1883]
And re-enable https://github.com/iotaledger/iota-sdk/pull/1687/files#diff-e55a410885ce608d553cac1a8ae845c88684ced36475b8747771c262c049378dR34

**Comment by Thoralf-M** [comment]
Done in Python, for nodejs we test the protocol parameters here https://github.com/iotaledger/iota-sdk/blob/9ad22f7556a5510a014577b83a145794a530ff37/bindings/nodejs/tests/client/infoMethods.spec.ts#L79 and for the other types we would need to rewrite it with something like https://zod.dev/?id=objects as the interfaces aren't available at runtime and that's not worth it just for this test
