### ISSUE TITLE
Use bigint Transformer

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#1896]
## Description

We should use  `@Transform((value) => hexToBigInt(value.value))` where  applicable instead of manual
like here: https://github.com/iotaledger/iota-sdk/blob/2b44b886538b3c5dbbaf55a8ace38e8f44273bfe/bindings/nodejs/lib/wallet/account.ts#L550

## Motivation

Easier to maintain

Downsides:
May need to change interfaces to classes, do we care?

**Comment by thibault-martinez** [comment]
We decided not to do this, manual is fine.
