### ISSUE TITLE
Add `WalletBuilder::with_address_generation_method` or something similar

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#1904]
## Description

Replace `WalletBuilder::with_bip_path` and `WalletBuilder::with_address` with a unifying builder method that ensures that `Wallet::bip_path` and `Wallet::address` cannot conflict in some way.

## Motivation

We can't allow fields `address` and `bip_path` have unrelated values.

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by Thoralf-M** [comment]
These three fields https://github.com/iotaledger/iota-sdk/blob/28f8c673a812a71143c0c9812e25b1253dff80e2/sdk/src/wallet/core/mod.rs#L106-L111 should also be moved out of it

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1941
