### ISSUE TITLE
Bring back `addresses_balance` method

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#1907]
## Description

This method allowed to get the balances of a list of arbitrary addresses, but was removed for some reason (maybe related to complexities that arose from unlock conditions like timelocks and expirations).
 
## Motivation

It seems to be a frequently requested feature so we should bring it back.

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by Thoralf-M** [comment]
Might be good to also have a method in the wallet for account addresses, which will then use the cached outputs from the wallet

**Comment by Thoralf-M** [comment]
Duplicate of https://github.com/iotaledger/iota-sdk/issues/604
