### ISSUE TITLE
ISA: allow account bound mana to be used as allotment

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1918]
If that makes sense maybe at least put a TODO or a debug log, otherwise might be hard to find later why this amount is not available

_Originally posted by @Thoralf-M in https://github.com/iotaledger/iota-sdk/pull/1900#discussion_r1471744917_

**Comment by Thoralf-M** [comment]
Done in https://github.com/iotaledger/iota-sdk/pull/1961
