### ISSUE TITLE
Align all Core API types and routes with TIP-48

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#1921]
## Description

Align all types and routes with [TIP-48](https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/tip48/tips/TIP-0048/openapi3-core.yaml)

## Motivation

Accurate implementation of the specification.

## Requirements

Write a list of what you want this feature to do.

- [x] Align SDK types
- [x] Update/Align Core binding
- [x] Align Python binding
- [x] Align NodeJs binding

## Open questions (optional)

What to do about `NodeInfoWrapper`? Should we ask for this to become part of the spec?

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1928
