### ISSUE TITLE
Change reissue_transaction_until_included() to await_block_inclusion()?

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1930]
Change reissue_transaction_until_included() to something like await_block_inclusion()? Reissuing doesn't work the same way anymore as before (if one block was already successfully sent) and requires more mana which needs to be alloted first, therefore it's probably better to just wait for inclusion of the block and if the tx doesn't get confirmed create a new one.

**Comment by Alex6323** [comment]
This seems related to #1867

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1979
