### ISSUE TITLE
Move delegation code out of ISA

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1937]
Was put there because we need the issuance but that should be solved later when we have finished the block/tx options refactoring.

**Comment by Alex6323** [comment]
`build_transaction.rs` was deleted in #1961, so this issue can be closed?

**Comment by thibault-martinez** [comment]
It hasn't been deleted, it's been moved. This code still exists in `input_selection/requirement/context_inputs.rs` so this issue can't be closed.

**Comment by Alex6323** [comment]
sure, but shouldn't we at least change the title of the issue then?

**Comment by thibault-martinez** [comment]
We won't do this in the end, it's fine the way it is now.
