### ISSUE TITLE
Refactor Block errors

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/iota-sdk#1957]
## Description

The block Error type is far too large and should be split into small, local errors for various modules that require them.

## Motivation

The error type is large and disorganized.

## Open questions

Can we find a stable `no_std` way to derive the display impl like `thiserror`?

## Are you planning to do it yourself in a pull request?

Yes

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2046
