### ISSUE TITLE
Bindings ClientOptions mismatch

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1982]
In Rust we flattened the fields of the client options https://github.com/iotaledger/iota-sdk/blob/0683d80776ff909b578bff1bda257ed61ebbd741/sdk/src/client/builder.rs#L36-L39, but in the binding types not (only NodeManagerBuilder)
https://github.com/iotaledger/iota-sdk/blob/0683d80776ff909b578bff1bda257ed61ebbd741/bindings/nodejs/lib/types/client/client-options.ts#L28-L30
https://github.com/iotaledger/iota-sdk/blob/0683d80776ff909b578bff1bda257ed61ebbd741/bindings/python/iota_sdk/types/client_options.py#L102-L103

**Comment by adricu** [comment]
Hi @Thoralf-M not sure if this is related, but we are having issues with typing in python when initializing the Wallet class.
ClientOptions seems that is not accepted and the class enforces a `dict[str, Any]` what IMHO it should accept both.

See the image attached:
![image](https://github.com/iotaledger/iota-sdk/assets/2545053/ce2e9206-28a6-4908-92bf-4c4ee5e68135)

**Comment by Thoralf-M** [comment]
Not related, but also needs to be fixed :+1:

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2042
