### ISSUE TITLE
Revert IdWithSlotIndex changes and add Util for computing slotIndex

### ISSUE THREAD

**Issue by msarcev** [iotaledger/iota-sdk#1987]
## Description

The solution added in this [PR](https://github.com/iotaledger/iota-sdk/pull/1962) doesn't work for Explorer, as `IdWithSlotIndex` being a subclass of build-in type `String` doesn't import properly.

We agreed in a [discussion in slack](https://iotafoundation.slack.com/archives/C041M474AKE/p1707817612797929) to revert those changes and simply add `Utils` to compute a slotIndex form block/transaction id. Something like:
```
static slotIndex(id: BlockId | TransactionId): number {
        const numberString = this.id.slice(-8);
        const chunks = [];
        for (
            let i = 0, charsLength = numberString.length;
            i < charsLength;
            i += 2
        ) {
            chunks.push(numberString.substring(i, i + 2));
        }
        const separated = chunks.map((n) => parseInt(n, 16));
        const buf = Uint8Array.from(separated).buffer;
        const view = new DataView(buf);
        return view.getUint32(0, true);
}
```

but with a call into rust bindings for the computation.

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1988
