### ISSUE TITLE
Update fixtures and re-enable commented tests

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#2015]
Re-enable tests that were commented in https://github.com/iotaledger/iota-sdk/pull/2013 when the fixtures are updated

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/iota-sdk/blob/388b5ffc0d29585d739ecd23d8a873f0101cb146/bindings/python/tests/test_api_responses.py#L30-L31

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2104
