### ISSUE TITLE
Re-investigate how we restore from a backup.

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#2032]
## Description

Currently we only use a difference in the `bip_path` to generally decide whether to ignore backup values, or not. We also ignore the backup silently, but I think we should put that into the log. Also I think it's debatable whether we should actually do that and not just fail, because the user might just be doing something wrong, like accidentally providing a wrong bip path.

Then we also have this nested check for the wallet address HRP before we actually restore. This probably could be cleaned up and consolidated, possibly into its own method.

This issue might possibly be resolved when we refactor the backup logic, see https://github.com/iotaledger/iota-sdk/pull/1934#discussion_r1494600871.

**Comment by thibault-martinez** [comment]
We have decided to not do this anymore.
