### ISSUE TITLE
Add mana field to `Build` enum variants

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#2039]
In the `Build` enum add a mana field to output variants that can contain mana
https://github.com/iotaledger/iota-sdk/blob/901fe28727fd53228f6d3a6357ff8d5e96c4e543/sdk/tests/client/mod.rs#L65

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2141
