### ISSUE TITLE
Update ProtocolParameters fixture

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#2040]
Update [ProtocolParameters fixture](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/tests/types/fixtures/protocol_parameters.json) when it got updated in the TIP https://github.com/iotaledger/tips/pull/154#discussion_r1492759962

https://github.com/iotaledger/iota-sdk/pull/2042/files#diff-ccbf2df2d2277881bef788920cfa81fc59eb20782d3d05c4666b41cc17a31ff9R85

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2095
