### ISSUE TITLE
Should we impl `Display` for `NodeInfoResponse` and `PermanodeInfoResponse`?

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#2051]
## Description

We have it for `InfoResponse` already so it seems consequential.

Note, that this issue takes the changes made by #1928 into account.

**Comment by Thoralf-M** [comment]
`PermanodeInfoResponse` is private, so no need there?

**Comment by thibault-martinez** [comment]
Not really necessary.
