### ISSUE TITLE
CLI: Refactor `InitParameters`?

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#2052]
## Description

- [x] does it make sense to have `localhost:8050` as the node default for the regular user?
- [x] does it make sense to have `4219/0/0/0` as the default bip path?
- [x] should we restrict certain coin types?
- [x] should we have individual fields on `InitParameters` for the bip path segments?

**Comment by Thoralf-M** [comment]
> does it make sense to have localhost:8050 as the node default for the regular user?

Maybe not, but currently we don't have a public network that's compatible with it, so for now I would keep it

> does it make sense to have 4219/0/0/0 as the default bip path?

How about removing the default and let the user choose from this, 4218/0/0/0, 1/0/0/0 or they can enter something else?
> should we restrict certain coin types?

I would say no

> should we have individual fields on InitParameters for the bip path segments?

I would say no
