### ISSUE TITLE
Emit block signing event with signing input

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#2054]
So the signing_input can be displayed in Firefly for ledger nano, similar to `TransactionProgressEvent::PreparedTransactionSigningHash`

We should probably also change the numbers of the TransactionProgress events so they match the order we emit them (SigningTransaction before PreparedTransactionSigningHash/PreparedTransaction) https://github.com/iotaledger/iota-sdk/blob/23623631126768f082def54531f7aaf9077b56be/sdk/src/wallet/operations/transaction/sign_transaction.rs#L39

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2100
