### ISSUE TITLE
Update bindings getValidator Return Type

### ISSUE THREAD

**Issue by brancoder** [iotaledger/iota-sdk#2057]
## Description

Update bindings for `getValidator` to return the `ValidatorResponse` instead of `ValidatorsResponse`
https://github.com/iotaledger/iota-sdk/blob/2.0/bindings/nodejs/lib/client/client.ts#L179
 
## Motivation

Explain why this feature is needed.

## Requirements

Write a list of what you want this feature to do.

1. 
2. 
3. 

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2059
