### ISSUE TITLE
Remove specific bech32 bindings converters in favour of AddressToBech32

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#2079]
- [ ] AccountIdToBech32
- [ ] AnchorIdToBech32
- [ ] NftIdToBech32

More?

**Comment by Thoralf-M** [comment]
- [ ] HexToBech32

**Comment by Thoralf-M** [comment]
Should we also remove `Bech32ToHex`? More error prone than using ParseBech32Address

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2151
