### ISSUE TITLE
Change HexPublicKeyToBech32Address to PublicKeyHash?

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#2080]
Conversion to bech32 address can be done with `AddressToBech32` and to get the public key hash one would need to convert it from bech32 back which is more annoying I think

In the bindings core we could replace it with `Blake2b256Hash` which could also be called in `ComputeAccountId, ComputeNftId` so we have less code there

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2135
