### ISSUE TITLE
Nodejs Bindings: fix a type error in CreateDelegationParams interface

### ISSUE THREAD

**Issue by cpl121** [iotaledger/iota-sdk#2083]
## Description

Interface `CreateDelegationParams` has param `delegatedAmount` as `NumericString`, but this amount has to be sent as a number, otherwise we will get the following error
`invalid type: string "200000000", expected u64 at line 1 column 157`

## Motivation

Type error

## Requirements

1. Modify the type of `delegatedAmount` from `NumericString` to `u64`

## Are you planning to do it yourself in a pull request?

No

**Comment by Thoralf-M** [comment]
Actually this is an issue on the Rust side https://github.com/iotaledger/iota-sdk/blob/8129e07d62d24e110dedfdefdce3e6d2ffbf9f95/sdk/src/wallet/operations/transaction/high_level/delegation/create.rs#L24 is missing a `#[serde(with = "string")]`

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2088
