### ISSUE TITLE
Python bindings should handle scientific notation of floats

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#2105]
As present in the MetricsResponse of the API

**Comment by Alex6323** [comment]
Can I get more information on this issue? In what sense can Python in particular not handle the scientific notation? Do you have an example or error message?

**Comment by Thoralf-M** [comment]
Decoding the metrics from the nodeinfo fails currently
```
"metrics":{"blocksPerSecond":"1.48E+01","confirmedBlocksPerSecond":"1.51E+01","confirmationRate":"1.0202702702702702E+02"}
```
but it's changed and moved to another endpoint atm https://github.com/iotaledger/iota.go/pull/703/files then we need to check again if it works fine or needs a custom decoder

**Comment by thibault-martinez** [comment]
Metrics has been moved out of info response.
