### ISSUE TITLE
Handle potential problems from submitting blocks

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#2111]
Handle potential problems from submitting the signed transaction in a block
https://github.com/iotaledger/iota-sdk/blob/37d52aae84960f087e0687d741e9e2e820ce2e7b/sdk/src/wallet/operations/transaction/mod.rs#L133-L146
In stardust we just reissued the transaction payload in new blocks, but with Mana and commitmentcontextinputs this isn't working fine anymore.
A block could potentially be submitted, but an error returned. A block could be submitted, but failed.
We should probably try to submit the block multiple times depending on the error we get and if it fails make sure to also set the transaction state correct and unlock its inputs

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2120
