### ISSUE TITLE
Reevaluate SignedTransactionPayload/Transaction::validate_length

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#2119]
Do we really need these? Shouldn't it be checked when building them already?

**Comment by Thoralf-M** [comment]
We could move the size checks into `verify_transaction()` https://github.com/iotaledger/iota-sdk/blob/c6b4d2ff63a8c3307e4592975f77114953f48486/sdk/src/types/block/payload/signed_transaction/transaction.rs#L451 and `verify_signed_transaction_payload()` to  `SignedTransactionPayload::new()` https://github.com/iotaledger/iota-sdk/blob/c6b4d2ff63a8c3307e4592975f77114953f48486/sdk/src/types/block/payload/signed_transaction/mod.rs#L36-L39
