### ISSUE TITLE
Improve tx error without account

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#2127]
Running https://github.com/iotaledger/iota-sdk/blob/2.0/bindings/nodejs/examples/how_tos/account_output/create.ts without an implicit account or account output before will silently fail in `submit_transaction_payload()` with `Failed to submit_transaction_payload account not found` and return a transaction id.
It probably shouldn't create the transaction in the first place, but we still need to allow preparing txs when they will be submitted by someone else

**Comment by thibault-martinez** [comment]
Has been fixed already.
