### ISSUE TITLE
[Task]: nodejs bindings: update interfaces with the new metadata feature

### ISSUE THREAD

**Issue by cpl121** [iotaledger/iota-sdk#2134]
## Description

Some interfaces like `CreateNativeTokenParams` and `MintNftParams` have outdated interfaces.
One of these parameters is the `foundryMetadata` or `immutableMetadata`, which was previously `HexEncodedString` type and now should be of type `MetadataFeature`

## Motivation

Outdated interface in nodejs bindings

## Requirements

Write a list of what you want this feature to do.

1. Modify type `HexEncodedString` by `MetadataFeature` of `immutableMetadata` in interface `MintNftParams`
2. Modify type `HexEncodedString` by `MetadataFeature` of `foundryMetadata` in interface `CreateNativeTokenParams`

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2194
