### ISSUE TITLE
Should we have both `GenerateEd25519Address` and `GenerateEd25519Addresses` method in the bindings?

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#2144]
## Description

Currently we have `GenerateEd25519Addresses` that creates a `Vec<Bech32Address>`, but most of the time the user probably just wants to create a single one!? We might also want to rename those methods to `GenerateBech32Ed25519Address`/`GenerateBech32Ed25519Addresses` so it aligns better with the returned type.

## Motivation

* not necessary anymore to provide a range of address indexes in most use cases.
* the result can be used directly without pulling it out of a vec/list

We could also include `bech32` in the method's name, so the returned format is clear.

**Comment by thibault-martinez** [comment]
We decided to keep both.
