### ISSUE TITLE
CLI: add `FAUCET_URL` environment variable

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#2166]
## Description

We have the `NODE_URL`  environment variable, that allows convenient configuration to which node the CLI wallet connects to, but we don't have that for the faucet, which usually also changes when you change the node (for example from private tangle to alphanet).

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2164
