### ISSUE TITLE
Add computeDelegationId() to bindings utils

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#2168]
Same as computeAccountId, just another name
https://github.com/iotaledger/iota-sdk/blob/c104506142e22f75c702abf2c4e901a7312c8387/bindings/python/iota_sdk/utils.py#L84
https://github.com/iotaledger/iota-sdk/blob/c104506142e22f75c702abf2c4e901a7312c8387/bindings/nodejs/lib/utils/utils.ts#L71

**Comment by marc2332** [comment]
Just asking, wouldn't it be better to just rename `computeAccountId` to something more generic instead of having two methods calling `blake2b256Hash` internally? Maybe calling it `blake2b256Hash` :laughing:

**Comment by Thoralf-M** [comment]
@marc2332 also thought about that already, but then users need to know that they need to hash the output id with blake2b256 to get the id, don't you think that's asking too much?

**Comment by marc2332** [comment]
> @marc2332 also thought about that already, but then users need to know that they need to hash the output id with blake2b256 to get the id, don't you think that's asking too much?

Haha, fair point, it's better for DX to have context-naming even though the internal logic is the same, will do a PR

**Comment by marc2332** [comment]
Ready! https://github.com/iotaledger/iota-sdk/pull/2172
