### ISSUE TITLE
[Bug]: Crash/Endless wait after claiming a large amount of native tokens

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/iota-sdk#217]
### Issue description

When trying to claim a large amount of native tokens, we will never get a response back from the `account.claimOutputs` call.
The manager can also not be destroyed after that. Only after killing the process and restarting, everything works again, with the output claimed. The limit between when it works and when not is ~1,451,000,000,000,000.

Maybe related to this:
When calling `account.prepareOutput` for sending ~1,451,000,000,000,000 tokens, the error `invalid output amount: 2772396040000000` is thrown, but sending the output afterwards works fine

`One time with and one time without expiration ULC. When we have no expiration ULC, the error gets thrown, and if we have it, it doesnt`

### Version

2.0.3-rc.27

### Expected behaviour

Claim output without error or endless loading

### Actual behaviour

Endless loading 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Send more than 1,451,000,000,000,000 native tokens with SDRUC from account A to account B (error should appear when preparing output)
2. On Account B, try claim the output -> endless load

### Errors

[wallet-2023-04-06-08-55.log](https://github.com/iotaledger/iota-sdk/files/11168321/wallet-2023-04-06-08-55.log)

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Claiming worked fine `[OUTPUT_CLAIMING] Claiming transaction created: block_id: Some(BlockId(0x57ec6efca945d11d1006ed902c913ed1219316dc3a222e0d6db8ebf0f4e779f2)) tx_id: TransactionId(0xb1534c417c68275af395acfc26c9e0b68a23f79fb85ce71bd46539d74ad158e1)`
https://explorer.shimmer.network/testnet/block/0x57ec6efca945d11d1006ed902c913ed1219316dc3a222e0d6db8ebf0f4e779f2

The first time you provided the native token amount as amount for the output, so this way it failed
```
prepare_output [94mDEBUG[0m [OUTPUT] prepare_output OutputOptions { recipient_address: "rms1qqctzt4p445zy5htsq0tr253y5pu96eckf3376rg03r33t5ylmgtx6kndp2", amount: 1455000000000000,
```
