### ISSUE TITLE
Update available balance for base coin

### ISSUE THREAD

**Issue by cpl121** [iotaledger/iota-sdk#2170]
## Description

Now the amount of `implicit account outputs` and `delegation outputs` is used to calculate the `available balance` of the `base coin`

## Motivation

Return an `available balance` more accurate, without using the amount of `implicit account outputs` and `delegation outputs`

## Requirements

Write a list of what you want this feature to do.

1. Return an available balance without using `implicit accounts` and `delegations` outputs of the wallet

## Are you planning to do it yourself in a pull request?

No

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2181
