### ISSUE TITLE
[Bug]: Cannot claim outputs sent to an Account address

### ISSUE THREAD

**Issue by marc2332** [iotaledger/iota-sdk#2214]
### Issue description

Can't claim outputs that are sent to an account address, we get a `no available inputs provided` error. We think this is because the SDK is filtering by the inputs available in the wallet and not the account, or somethng like that.

### Version

latest commit on 2.0

### Expected behaviour

Allow us to claim

### Actual behaviour

`no available inputs provided`

### Can the issue reliably be reproduced?

Yes

### Errors

`no available inputs provided`

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Do the outputs show up in the unspent outputs of the wallet? Do you sync with provided AccountSyncOptions?

**Comment by marc2332** [comment]
I can't currently reproduce this anymore, I'll let you know if this pops up again

**Comment by thibault-martinez** [comment]
Have you been able to reproduce this?

**Comment by marc2332** [comment]
> Have you been able to reproduce this?

negative
