### ISSUE TITLE
[Bug]: Expiration unlock condition 'slot' field

### ISSUE THREAD

**Issue by msarcev** [iotaledger/iota-sdk#2217]
### Issue description

The field in the deserialized EUC is `slot` while the typescript models define `slotIndex`

```
{"type":3,"returnAddress":{"type":8,"accountId":"0x21c983484baec0435205ba1a4c31ef0e66565fd84c93b086ca4c91ec8b9a65e5"},"slot":17724}
```

VS

```
declare class ExpirationUnlockCondition extends UnlockCondition {
    readonly returnAddress: Address;
    readonly slotIndex: SlotIndex;
    constructor(returnAddress: Address, slotIndex: SlotIndex);
}
```

### Version

2.0

### Expected behaviour

N/A

### Actual behaviour

N/A

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
https://github.com/iotaledger/iota-sdk/pull/2215 ?

**Comment by thibault-martinez** [comment]
Can/Should this be closed?
