### ISSUE TITLE
Add bindings format checks to CI

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#246]

**Comment by Thoralf-M** [comment]
This is done
Rust: https://github.com/iotaledger/iota-sdk/blob/cc28bfdbadd250b07ce0e1d55b616961f7154a2e/.github/workflows/lint.yml#L100
Nodejs: https://github.com/iotaledger/iota-sdk/blob/cc28bfdbadd250b07ce0e1d55b616961f7154a2e/.github/workflows/bindings-nodejs.yml#L97
Python: https://github.com/iotaledger/iota-sdk/blob/cc28bfdbadd250b07ce0e1d55b616961f7154a2e/.github/workflows/bindings-python.yml#L42
wasm: https://github.com/iotaledger/iota-sdk/blob/cc28bfdbadd250b07ce0e1d55b616961f7154a2e/.github/workflows/bindings-wasm.yml#L104
