### ISSUE TITLE
CLI: handle CTRL-L to clear the terminal page

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#260]

**Comment by qrayven** [comment]
At the moment the implementation of `CTRL-L` is a little bit tricky. In the current implementation https://github.com/iotaledger/iota-sdk/blob/a7ab53804429f6dc3eda5771373f0fd97f4b393e/cli/src/account.rs#L50, we use `dialoger` and `interact_text()` which doesn't allow creating a handler for all terminal events.  If we wanted to use `interact()` we would have lost the implementation of `history` and `autocomplete`.  The most elegant solution would be to create PR to `dialoger`  which would allow access to all terminal events when `interact_text()` is used. 

Also, there is a chance the `dialoger` will support `ctrl-l` out of the box: https://github.com/console-rs/dialoguer/issues/230

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1238
