### ISSUE TITLE
CLI: Add NTs/NFTs/Aliases/Foundries to addresses overview

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#261]
## Description

Add NTs/NFTs/Aliases/Foundries to addresses overview
https://github.com/iotaledger/iota-sdk/pull/259#discussion_r1166529957
Probably should reuse something from the account.balance() method

## Motivation

Better visibility of what belongs to which address

## Open questions (optional)

Do we want to have the full balance object for every address or is that too large?

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1179
