### ISSUE TITLE
Add _key_api_ref_link to wiki

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#273]
## Description

Currently we have the  _key_api_ref_link files in the documentation section but don't use them. Now that we have api reference links for all languages we could add those files to the "how-tos".

## Requirements

1. Check if links are still valid
2. Add to related "how-tos"
3. Enjoy links with further info in "how-tos"

## Are you planning to do it yourself in a pull request?

No.

**Comment by Dr-Electron** [comment]
As we are now starting with the new SDK docs this is the perfect moment to add those in a consistent manner.
For reference this is refering to the old docs in [iota.rs](https://github.com/iotaledger/iota.rs) and [wallet.rs](https://github.com/iotaledger/wallet.rs)

**Comment by Dr-Electron** [comment]
@thibault-martinez We can add this to another milestone if you want. We probably won't have too much time for it with the wiki merge and the 1.0 SDK release. And this isn't a high prio anyway

**Comment by thibault-martinez** [comment]
Ok, will move it to 1.1 then.
