### ISSUE TITLE
Validate HRP in Bech32Address::new

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#275]
Waiting for progress on https://github.com/rust-bitcoin/rust-bech32/issues/99

**Comment by kwek20** [comment]
Should probably do this in #366 
Merge request here now: https://github.com/rust-bitcoin/rust-bech32/pull/103

**Comment by DaughterOfMars** [comment]
It looks like their `Hrp` type is more-or-less identical to mine, so we should be able to swap it out pretty easily once there is a release.
