### ISSUE TITLE
Merge sequential examples

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/iota-sdk#288]
## Description

There are many examples that are intended to be run sequentially, but they are individual examples. I propose that we merge these examples into one.

## Motivation

- Running the examples out of sequence can cause errors to occur, which is an atypical practice in the rust community.
- There is a great deal of syncing and duplicated code that occurs in each example to pick up from the last.

## Requirements

The examples which must be run in sequence should instead be runnable as a single example.

## Open questions (optional)

Is inspecting the state between examples important? If so, this may not be a good change. However, we could still make that work using a single example.

**Comment by thibault-martinez** [comment]
We don't really have a lot of sequential examples anymore, and the ones that are sequential are part of the wiki and the order is better explained.
