### ISSUE TITLE
Define a naming scheme for recipient addresses and sent data

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/iota-sdk#290]
## Description

There are instances in the code where we send some data to a recipient address, and we therefore have many Key-Value structs to support these.

```rust
pub struct AddressWithAmount {
    address: String,
    amount: u64,
    return_address: Option<String>,
    expiration: Option<u32>,
}

pub struct AddressNativeTokens {
    pub address: String,
    pub native_tokens: Vec<(TokenId, U256)>,
    pub return_address: Option<String>,
    pub expiration: Option<u32>,
}

pub struct AddressAndNftId {
    pub address: String,
    pub nft_id: NftId,
}
```
This leads to fields with long, awkward names that still do not adequately describe their usage:
```rust
addresses_and_nft_ids: Vec<AddressAndNftId>,
```

I propose that we define a keyword for these Key-Value-like structs to unify them.

### Suggestions

- Package (ex. `BaseTokenPackage`, `NftPackage`)
- Parcel (same as above, but perhaps more associated with mail and sending)
- Packet
- Bundle

Please comment with any other suggestions you have.

**Comment by kwek20** [comment]
hm i feel like surely theres a tip somewhere that has a name for these fields collected.
i see the word "schema" mentioned for example here: https://github.com/iotaledger/tips/blob/main/tips/TIP-0027/tip-0027.md#nft-schema

**Comment by Thoralf-M** [comment]
@kwek20 this TIP is for the NFT immutable metadata feature

**Comment by kwek20** [comment]
Sure i just meant an example of wording we use in different tips
