### ISSUE TITLE
Find a way to cleanly print wallet and account help

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#296]
## Description

We use this logic to print the help programmatically: 
```
if let Err(err) = WalletCli::try_parse_from(vec!["Wallet:", "help"]) {
    println!("{err}");
}
```
If I understand correctly ... we print the error which just contains the help text because `try_parse_from` failed. Is there no clean way to achieve this that doesn't involve error logic?

## Motivation

The code is weird.

## Open questions (optional)

Maybe this is the way. I dunno. My dark saber is broken.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1154
