### ISSUE TITLE
Harmonize bindings address generation test

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#30]
### Task description

For https://github.com/iotaledger/iota-sdk/issues/73 we added address generation tests to bindings.
However each binding uses a different seed/mnemonic.

### Requirements

equal address generation asserts across all bindings

### Acceptance criteria

equal address generation asserts across all bindings

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Thoralf-M** [comment]
In Rust and Python we use test_vectors.json, so only nodejs needs to be updated to this
https://github.com/search?q=repo%3Aiotaledger%2Fiota-sdk%20test_vectors&type=code

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1336
