### ISSUE TITLE
Add support for generating EVM addresses

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/iota-sdk#337]
## Description

This is needed so that Firefly users can generate deposit addresses for L2 EVM-based chains using their existing Strongholds.

## Motivation

Because Stronghold is used to derive addresses from the master seed for regular Ed25519 addresses and that seeds do not come out once placed in the "vault", we need this functionality implemented.

## Requirements

1. Return a string of a valid Ethereum address given a few parameters (this should be a method on an account).

For example,
```typescript
interface IAddressGenerationOptions {
    index?: number // default is 0th index
    internal?: boolean // default is external
}

interface IAccount {
    ...,
    /**
     * If no options are provided, use defaults commented above.
     */
    generateEvmAddress(options?: IAddressGenerationOptions): Promise<string>
}
```

## Open questions (optional)

None.

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
This should be a SecretManager method

**Comment by Thoralf-M** [comment]
Requires https://github.com/iotaledger/crypto.rs/pull/187 and updated Stronghold first

**Comment by DaughterOfMars** [comment]
Old message interface included?

**Comment by DaughterOfMars** [comment]
Should this become a new trait fn for `SecretManage`?
