### ISSUE TITLE
[Bug]: Arithmetic Operation Overflow panic

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/iota-sdk#350]
### Issue description

I get this panic when claiming native tokens in Firefly. In my case I am using a personally created native token called Bottlecaps with a circulating supply of 100,000,000,000 CAPS and Supply with a supply of 1000 SPLY. This panic then causes Firefly's calls to the wallet api to fail and the app must be restarted to work again.

It isn't reproducible on every single claim transaction but it happens reliably enough that I can reproduce it within a handful of transactions. Just a hunch, but seems to happen more on smaller transactions.

Here are the token IDs on the testnet:
Bottlecaps - 0x086b74bdfad3b7d6f45455b35bcd9b03607941f1bcfe6cf01d590b2893ea69dc6d0100000000
Supply - 0x086b74bdfad3b7d6f45455b35bcd9b03607941f1bcfe6cf01d590b2893ea69dc6d0200000000

Perhaps related to #264 but this has reliable steps to reproduce

### Version

v2.0.3-rc.32

### Expected behaviour

To be able to claim the native token transaction or the panic to produce an error and allow the iota-sdk to continue working.

### Actual behaviour

Claiming a transaction causes an `'arithmetic operation overflow'` panic and causes all send and receive transaction on Firefly Shimmer to hang until the app is restarted.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

For Bottlecaps
1. On Wallet 1, create the Bottlecaps asset with 100_000_000_000 circulating supply.
2. Send 95 Bottlecaps to Wallet 2 on the same profile without gifting the storage deposit
3. On Wallet 2, claim the 95 Bottlecaps (no panic here)
4. Back in Wallet 1, send 5 Bottlecaps to Wallet 2 without gifting the storage deposit
5. On Wallet 2, claim the 5 Bottlecaps (this causes the panic)

For Supply
1. On Wallet 1, create the Supply asset with 1_000 circulating supply.
2. Send 1 Supply to Wallet 2 on the same profile without gifting the storage deposit
3. On Wallet 2, claim the 1 supply (this first transaction didn't cause the panic)
4. Back in Wallet 1, send another 1 Supply to Wallet 2 without gifting the storage deposit
5. On Wallet 2, claim the 1 supply (this second transaction caused the panic)

### Errors

```
thread '<unnamed>' panicked at 'arithmetic operation overflow', /Users/krafjts/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.12.1/src/lib.rs:38:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Alex6323** [comment]
I couldn't trigger it anymore using your provided steps. That could be a good thing. I consider it not unlikely that https://github.com/iotaledger/iota-sdk/pull/330 indeed fixed the issue. Can you try to trigger it using our CLI wallet? I can guide you through it if you're not familiar with it. @kraftjs

**Comment by Thoralf-M** [comment]
No longer occurs
