### ISSUE TITLE
[Feature: Rust and bindings] Sign arbitrary bytes with public key

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/iota-sdk#351]
## Description and Motivation

As per the [token registry whitelist](https://github.com/iota-community/token-whitelist) requirement:
> You must supply an Ed25519 signature within the PR description which signs the JSON data together with the corresponding public key (not the Ed25519 address).

There is a need to be able to sign arbitrary data (a JSON in this case) to submit this information and list NFTs or Native Tokens to the token-whitelist mentioned above.

## Requirements

Write a list of what you want this feature to do.

1. Be able to sign arbitrary bytes
2. Be able to select the public key (if I used account 2 or 3, or wallet 2 or 3 as they are called in Firefly to mint the tokens or NFTs, from the same mnemonic)

## Are you planning to do it yourself in a pull request?

No

**Comment by Thoralf-M** [comment]
It's already possible with sign_ed25519()
For the address to use, you need to provide the bip32 path, https://github.com/iotaledger/iota-sdk/pull/353 will make this easier

**Comment by thibault-martinez** [comment]
I think Antonio wanted us to write an example for it, but the issue doesn't really reflect that.
