### ISSUE TITLE
QA: proofread SDK wiki

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#390]
https://wiki.iota.org/next/iota-sdk/welcome/

- Read everything
- Look for typos
- Look for errors
- Consider yourself a complete novice and see if everything is well explained and makes sense

**Comment by thibault-martinez** [comment]
- [ ] AlexS
- [x] AlexC
- [ ] Thoralf
- [ ] Brord
- [ ] Pawel
- [ ] Thibault
- [ ] Abdul

**Comment by DaughterOfMars** [comment]
Yes, uhhhh, "pretend" I'm a complete novice. 😰

**Comment by DaughterOfMars** [comment]
My notes:

- [ ] [This section](https://wiki.iota.org/next/iota-sdk/about-the-iota-sdk/#your-application-in-the-iota-network) is slightly confusing. It mentions Testnet in the text but Devnet in the image. Also, there is some inconsistency with casing in the image text.
- [ ] [This](https://wiki.iota.org/next/iota-sdk/explanations/account-approaches/) is a bad title, imo. I would probably just use `Accounts`.
- [ ] The phrasing [here](https://wiki.iota.org/next/iota-sdk/explanations/account-approaches/#single-account-approach) is weird.
- [ ] [Here](https://wiki.iota.org/next/iota-sdk/explanations/testnet-and-test-tokens/#get-test-tokens) could be reworded, feels clunky.
- [ ] [This page](https://wiki.iota.org/next/iota-sdk/how-tos/accounts-and-addresses/create-mnemonic/) could use more detailed explanation about the purpose and usage of mnemonics.
- [ ] [This subtitle](https://wiki.iota.org/next/iota-sdk/how-tos/accounts-and-addresses/create-account/) feels unnecessary. There are more examples of this (restating the title) in other How-Tos.
- [ ] Incomplete sentence in the [subtitle](https://wiki.iota.org/next/iota-sdk/how-tos/accounts-and-addresses/create-address/)
- [ ] [This page](https://wiki.iota.org/next/iota-sdk/how-tos/advanced-transactions/send-micro-transaction/) definitely warrants more explanation.
- [ ] `Use Aliases/NFTs as Wallets` could definitely use more explanation.
- [ ] No explanation on [this page](https://wiki.iota.org/next/iota-sdk/how-tos/sign-and-verify-ed25519/sign-ed25519/) or [this page](https://wiki.iota.org/next/iota-sdk/how-tos/sign-and-verify-ed25519/verify-ed25519-signature/)
- [ ] Lots of typos [here](https://wiki.iota.org/next/iota-sdk/how-tos/outputs/features/)
- [ ] Inconsistent phrasing in NFT How-Tos.
- [ ] In general, there should be more links to further reading on basic topics.
- [ ] More explanation about node health, or a link, [here](https://wiki.iota.org/next/iota-sdk/how-tos/client/get-health/)
- [ ] Clunky phrasing [here](https://wiki.iota.org/next/iota-sdk/how-tos/client/get-info/) and [here](https://wiki.iota.org/next/iota-sdk/how-tos/client/get-outputs/)
- [ ] [This](https://wiki.iota.org/next/iota-sdk/references/rust-api-reference/) does not link to anywhere useful, and it's strange to suggest building the docs locally when there is a public instance.
- [ ] [This](https://wiki.iota.org/next/iota-sdk/troubleshooting/#stackexchange) needs a space, and there are typos and clunky phrasing in the text.
- [ ] [This page](https://wiki.iota.org/next/iota-sdk/contribute/) could use a rewrite.

**Comment by Alex6323** [comment]
I collect my notes here (ongoing!):

https://hackmd.io/U4pXAsuGS4Gd0-gLVPYS6A

**Comment by thibault-martinez** [comment]
From Antonio https://hackmd.io/@IOTA-X-TEAM/Sk7QxtKun
