### ISSUE TITLE
QA: write and review iota.rs/wallet.rs to iota-sdk migration documentation

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#398]
Step by step guide on how to transition from the past crates to the SDK.

**Comment by luca-moser** [comment]
Any updates on this? I still think we need such a migration guide for the IOTA SDK given that also the Stronghold snapshot format has been changed etc.

**Comment by thibault-martinez** [comment]
We had these two examples for the stronghold/database migration
https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/examples/wallet/migrate-db-chrysalis-to-stardust.ts
https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/examples/wallet/migrate-stronghold-snapshot-v2-to-v3.ts
