### ISSUE TITLE
Create Accounts and Addresses examples with related docs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#410]
## Description

Create examples for the `Accounts and Addresses` section. It should contain:
- [x] Create mnemonic
- [x] List addresses
- [x] Create an account
- [x] Create an address
- [x] List accounts
- [x] List outputs
- [x] List transactions
- [x] Check balance

## Are you planning to do it yourself in a pull request?

Yes, someone from out team will work on it.

**Comment by Thoralf-M** [comment]
Shouldn't `Check unlock conditions` rather be part of https://github.com/iotaledger/iota-sdk/issues/411?

**Comment by Dr-Electron** [comment]
> Shouldn't `Check unlock conditions` rather be part of #411?

Shouldn't Check unlock conditions rather be part of https://github.com/iotaledger/iota-sdk/issues/411?

Yeah we can change that I guess
