### ISSUE TITLE
Create Output Unlock Conditions examples with related docs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#411]
## Description

Create examples for the `Output Unlock Conditions` section. It should contain:

Output Unlock Conditions
- [ ] Address 
- [ ] Timelock
- [ ] Check unlock conditions

Storage-deposit-return
- [ ] Send Micro Transaction
- [ ] Receive Micro Transaction

Expiration
- [ ] Send
- [ ] Claim non expired
- [ ] Claim expired

## Are you planning to do it yourself in a pull request?

Yes, someone from out team will work on it.

**Comment by Dr-Electron** [comment]
I would change this layout a little bit.
I would add a section which is called `Advanced Transactions` or something, which explains how to create a micro transaction (later we could also explain other `TransactionOptions`) and another example which explains how to use custom outputs with the `send` function with a reference to the output section (to create your own outputs).

So it would look something like:

Advanced Transactions

- [ ] Send Micro Transaction
- [ ] Advanced Transaction(?)
- [ ] Claim examples

**Comment by thibault-martinez** [comment]
@Dr-Electron Were these actually all implemented, yeah?

**Comment by Dr-Electron** [comment]
> @Dr-Electron Were these actually all implemented, yeah?

Yes I would say so. With the info in the how tos you should be able to build everything mentioned in the initial list
