### ISSUE TITLE
Create Alias Outputs with related docs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#413]
## Description

Create examples for the `Alias Output` section. It should contain:
- [ ] Create 
- [ ] Governance Transitions
- [ ] State Transitions
- [ ] Unlock Alias Funds
- [ ] Destroy

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by anistark** [comment]
Opened [PR](https://github.com/iotaledger/iota-sdk/pull/686) to create and destroy alias.
