### ISSUE TITLE
Create NFTs examples with related docs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#415]
## Description

Create examples for the `NFTs` section. It should contain:

- [ ] Burn
- [ ] Transfer
- [ ] Transfer with Storage Deposit Return and Expiration
- [ ] Claim
- [ ] Claim under conditional Transfer
- [ ] Introduction
- [ ] Mint
- [ ] Create NFT collections

## Are you planning to do it yourself in a pull request?

Yes, someone from out team will work on it.

**Comment by antonionardella** [comment]
I'll try my hand here  

* [ ] Read NFT metadata
* [ ] Query all NFTs of a collection
* [ ] Query addresses owning a certain NFT collection

**Comment by luca-moser** [comment]
Status update on this:
- Rust/NodeJs bindings are done.
- Ani is currently figuring out the problems he has with running/using the Python bindings.

**Comment by thibault-martinez** [comment]
> * Ani is currently figuring out the problems he has with running/using the Python bindings.

@anistark Do you need help with this?
