### ISSUE TITLE
Remove useless DTOs

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#430]
- [x] All ID DTOs like AliasIdDto, since they are string_serde_impl anyway (https://github.com/iotaledger/iota-sdk/pull/448)
- [x] AccountBalanceDto
- [x] CreateAliasParamsDto
- [x] AssetsDto
- [x] OutputParamsDto
- [x] RentStructureDto
- [x] NativeTokenDto
- [x] MintNativeTokenParamsDto
- [x] NativeTokensBalanceDto
- [x] BalanceDto
- [x] MintNftParamsDto

**Comment by kwek20** [comment]
Mayeb also:
- [ ] `PreparedTransactionDataDto `
- [ ] `PreparedMintTokenTransactionDto`
