### ISSUE TITLE
Improve `Send` struct creation

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/iota-sdk#470]
Just thinking out loud: is there no way to make this a bit better UX wise? What if we have a `SendNftParams` constructor that takes a Bech32AddressLike? It would make it fallible but we already have a fallible thing here, I don't think it would matter much but would make the overall thing a bit better?

_Originally posted by @thibault-martinez in https://github.com/iotaledger/iota-sdk/pull/366#discussion_r1198732382_

We can add builder patterns for these as a convenience.

**Comment by thibault-martinez** [comment]
- [ ] `SendAmountParams::new::address` as `TryInto<Bech32Address>` ?
- [ ] `SendNftParams` constructor
- [ ] `SendNativeTokensParams` builder?
- [ ] `MintNftParams` builder?
