### ISSUE TITLE
Replace our `Hrp` with the bech32 crate one

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#472]
Waiting for a new release of the bech32 crate with this change https://github.com/rust-bitcoin/rust-bech32/issues/99

**Comment by tcharding** [comment]
Its out now https://docs.rs/bech32/0.10.0-alpha/bech32/primitives/hrp/struct.Hrp.html

Hope you find it useful.

**Comment by thibault-martinez** [comment]
> Its out now https://docs.rs/bech32/0.10.0-alpha/bech32/primitives/hrp/struct.Hrp.html
> 
> Hope you find it useful.

Thanks, will try it in the next few days.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1413
