### ISSUE TITLE
Consistent error is thrown when account cannot cover storage deposit

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/iota-sdk#480]
## Description

When Firefly tries to claim transactions that cannot be claimed due to no outputs available for covering the storage deposit, different type of errors are thrown per output. As an example.

If I have two incoming NFT Outputs that need claiming, but I only have one output with SMR, then I get the following error if I try to claim the transaction:

`{type: 'insufficientFunds', error: 'insufficient funds 0/70500 available'}`

If I have two incoming Basic Outputs with SD requirements in the same scenario, the following error is thrown:

`{type: 'block', error: 'insufficient output amount for storage deposit: 1 (should be at least 42600)'}`

If I want to attach extra storage deposit that I don't have due to pending transaction, the following error is thrown:

`{type: 'client', error: 'insufficient amount: found 125000, required 133000'}`

## Motivation

Consistent Error Handling, if  a transaction cannot be confirmed for the same reason

## Requirements

Write a list of what you want this feature to do.

1. Consistently throw one error: our preferred one is `{type: 'insufficientFunds', error: 'insufficient funds 0/70500 available'}`
2. Check whether there are other places where a similar error should be thrown that we missed

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
> If I want to attach extra storage deposit 

What does this mean?

**Comment by Tuditi** [comment]
> > If I want to attach extra storage deposit
> 
> What does this mean?

![image](https://github.com/iotaledger/iota-sdk/assets/45079109/044e4a6d-58e3-4dd1-aa92-3718ae82c36e)

If my NFT Output doesn't contain enough SD due to adding another unlock condition, then I have to attach more glow with it. This requires a basic output that is not used in a pending transaction.
