### ISSUE TITLE
Introduce `change_account` command to quickly switch between accounts

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#487]
## Description

^

## Motivation

Well, we gotta go Premium! :sunglasses:

## Open questions (optional)

Who's going to be the fastest to switch accounts?

## Are you planning to do it yourself in a pull request?

I would do it.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1043
