### ISSUE TITLE
NodeJS to accept numbers when it applies

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#490]
## Description

Sometimes we ask for hexencoded numbers in nodejs.
This makes usage less smooth, we should switch to number.

We could use a [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) for this

## Motivation

UX

## Requirements

Write a list of what you want this feature to do.

1. `HexEncodedAmount` to change to number externally

## Open questions (optional)

What do do about `HexEncodedString`
- Update OutputId and friends to use HexEncoded when possible

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by Dr-Electron** [comment]
Added it to our project too, so we can track progress. Great minds think alike :trollface:

**Comment by kwek20** [comment]
@Dr-Electron What do you think we should do with HexEncodedString? Not very nice UX wise to must send encoded.

**Comment by Dr-Electron** [comment]
Yeah ideally a user shouldn't see that at all 🤔 At least not in the higher  level functions.
So ideally utf8tToHex is a function which is called internally and not by the user.

**Comment by lucas-tortora** [comment]
Just a quick comment, I think we have the same issue with the Python binding.
