### ISSUE TITLE
Provide functions to create TIP27 and TIP30 compatible assets

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#504]
## Description

We should provide a function/class to provide TIP27 or TIP30 compatible data. But ideally we probably create helper functions like `mint_IRC27_nft` or `mint_IRC30_token`. (Could also just be `mint` from different namespaces)

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
Not breaking change, we'll do it in 1.1.
