### ISSUE TITLE
Listen to MQTT. Shimmer transactions https://wiki.iota.org/shimmer/iota.rs/how_tos/mqtt/

### ISSUE THREAD

**Issue by abcen7** [iotaledger/iota-sdk#506]
## Description

Need to release that: https://wiki.iota.org/shimmer/iota.rs/how_tos/mqtt/

## Motivation

Bivreost is need this feature to get external transactions for the wallet

## Requirements

Create a Client which will connect to the [Shimmer Testnet](https://api.testnet.shimmer.network/).
Subscribe to a set of topics.
Listen to the topic defined in step 2 and log the output.

## Are you planning to do it yourself in a pull request?

No.

**Comment by Dr-Electron** [comment]
@thibault-martinez guess this should still be in v1.0 as we need to make sure the bindings have the same features

**Comment by abcen7** [comment]
HELLO GUYS, HOW IS YOUR WORK ABOUT THIS PROBLEM, PLEASE RELEASE THAT, WE REALLY NEED THIS FEATURE TO OUR PRODUCTION WALLET!!!!!!!!
