### ISSUE TITLE
`Ed25519Signature` could use stronghold/crypto types

### ISSUE THREAD

**Issue by DaughterOfMars** [iotaledger/iota-sdk#511]
## Description

```rust
pub struct Ed25519Signature {
    public_key: [u8; Self::PUBLIC_KEY_LENGTH],
    #[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
    signature: [u8; Self::SIGNATURE_LENGTH],
}
```

This could potentially use the PublicKey and Signature types from stronghold/crypto.

**Comment by thibault-martinez** [comment]
But these are actually define with the crypto ones so what do you mean? You'd just remove them?

**Comment by DaughterOfMars** [comment]
I mean we cold potentially use strongholds `PublicKey` and `Signature` type instead of the arrays.

**Comment by thibault-martinez** [comment]
Ah alright, thought you meant the constants

**Comment by DaughterOfMars** [comment]
It would be immensely helpful if the crypto types would derive basic things like `Copy, Clone, Eq, PartialEq, etc`. Otherwise we'll have to work around that. I'll create a PR on crypto for this.
