### ISSUE TITLE
Rename native token functions

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#543]
## Description

I would suggest renaming some native token functions. 
- `mint_native_token`
- `increase_native_token_supply`
- `decrease_native_token_supply`

## Motivation

Currently the functions don't really describe what they are are doing.

## Requirements

1. Rename  `mint_native_token` to `create_native_token`
2. Rename `increase_native_token_supply ` to `mint_native_token` or something that describes the change of the circulating supply
3. Rename `decrease_native_token_supply` to `melt_native_token` or something that describes the change of the circulating supply

## Are you planning to do it yourself in a pull request?

No

**Comment by thibault-martinez** [comment]
We'll do that in 1.0.
