### ISSUE TITLE
Create send wrapper functions in bindings

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#544]
## Description

We should have wrapper functions for all `prepare...` functions, so that one can just use `send...`

## Motivation

We have the same functionality in Rust and it should be available in the bindings too.

## Are you planning to do it yourself in a pull request?

No

**Comment by thibault-martinez** [comment]
This is not breaking change so we may add it in the future, maybe 1.1, for now prepare + send should be enough.
