### ISSUE TITLE
Create instances for single native tokens

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#545]
## Description

I guess it would be nice to have "Instances" for native tokens which all implement a common "transfer" interface.
That way you could get the token instance from an account by doing something like:
```
token = account.get_token(id)
```
Afterwards you could use functions like:
```
token.send(address, amount)
token.burn(amount)
...
```

## Motivation

This would make it easier to handle single tokens

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
I don't know about that. It would force the token to hold a reference to the account, which would be a bit annoying.
Also, it would be a completely different API compared to the rest.

**Comment by kwek20** [comment]
We do have precedence for this in the `PrepareTransactionData` wrappers from the bindings, and its nice to have. I dont think its really high priority though ;)

**Comment by Dr-Electron** [comment]
As I said in internal discussions, this is end level of DX imo. But I wanted to write it down somewhere.
And maybe it would be nice to have in mind for 2.0

**Comment by thibault-martinez** [comment]
Maybe a nice feature to have but not breaking change and very much premium. I'll put it in 1.1 for now as it's not breaking change but we may decide to do it for 2.0 only later.

**Comment by Dr-Electron** [comment]
Sure. I think it's nice to keep in the back of your head. Even 2.0 is fine for me. But I think the current system should change somehow 👍

**Comment by thibault-martinez** [comment]
We decided against doing this, we don't want to hold a reference to the wallet.
