### ISSUE TITLE
Allow providing a mnemonic in the StrongholdSecretManager builder

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#549]
## Description

I have this use-case in the cli-wallet `init_command` fn:

```rust
let secret_manager = StrongholdSecretManager::builder()
    .password(&password)
    .build(snapshot_path)?;
// TODO: allow providing the mnemonic in the builder?
secret_manager.store_mnemonic(mnemonic).await?;
let secret_manager = SecretManager::Stronghold(secret_manager);
```

## Motivation

Ergonomics.

## Open questions (optional)

I haven't investigated this deeply enough as to why this doesn't exist already. There might be a good reason for it.

## Are you planning to do it yourself in a pull request?

I would do it.

**Comment by DaughterOfMars** [comment]
After thorough investigation, I do not believe this is feasible without making the build function `async`, which I think would worsen the ergonomics in general.

**Comment by Alex6323** [comment]
Yeah, I don't think we're going to switch to sync locks for this. Also there are other problems like the order of how you'ld call the builder methods (password must be set before mnemonic and so on ...) which makes me realize that it's too much work to redesign this and it's probably not going to be worth the effort anyway. However, I still would have liked if setting up a *new* stronghold could be possible with providing everything atomically in one builder call, which would then ensure that a "built" stronghold instance was always something in a complete and valid state.

So ... I am fine with closing the issue.
