### ISSUE TITLE
SSLContextFactory support for Self-signed certificates when connecting to private tangles.

### ISSUE THREAD

**Issue by sikhness** [iotaledger/iota-sdk#56]
## Description

Currently there is no way to configure the SSLContextFactory to provide a way to support self-signed certificates when connecting to private tangles to communicate with them securely.  When trying to connect to a private tangle which has a self-signed certificate (HTTPS), the following error is thrown by the API currently, `Error: error sending request for url (https://localhost:14266/health): error trying to connect: invalid certificate: UnknownIssuer`.

## Motivation

This will allow for the Java API to connect to private tangles that are secured using self-signed certificates (HTTPS) as you can provide the certificate store within the code, instead of having to communicate with them unsecured (HTTP).

## Requirements

Write a list of what you want this feature to do.

1. Expose an SSLContextFactory option to provide your own certificate stores

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
This should be fixed by https://github.com/iotaledger/iota-sdk/pull/300, let us know if it's still happening.
