### ISSUE TITLE
Fix optional transaction note

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#569]
## Description

Fix optional transaction note, currently it's just always set to None https://github.com/iotaledger/iota-sdk/blob/bf7e2a8c9895d3fb88d83ffdf2ce94b1f778c406/sdk/src/wallet/account/operations/transaction/mod.rs#L179
instead it should use what's provided in the TransactionOptions https://github.com/iotaledger/iota-sdk/blob/bf7e2a8c9895d3fb88d83ffdf2ce94b1f778c406/sdk/src/wallet/account/operations/transaction/options.rs#L31

A test should be added which sends a transaction with a note and then checks if the note is set

**Comment by thibault-martinez** [comment]
`submit_and_store_transaction` doesn't have access to the options though. I can add them.
