### ISSUE TITLE
Refactor send functions

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#586]
## Description

I see multiple issues with our send functions. Let's use this issue to discuss them and eventually split it up in multiple issues if needed:

1) Our basic send function is called `send_amount`. And our "advanced" or send output function is called `send` (although in the bindings we call it send_outputs/sendOutputs). I think it should be the other way around:
You want to send something without any fancy stuff? Use `send`. 
You need more advanced outputs? Use `send_outputs`

2) SendAmountParams:
a) Do we really need that as it's own object, class struct? Can't the send function be `send(amount, address, options)`?
b) If we keep it, can we rename the var to something else than `output` in the examples? It's confusing 😆 . Let's call it params or something

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
> 1. Our basic send function is called `send_amount`. And our "advanced" or send output function is called `send` (although in the bindings we call it send_outputs/sendOutputs). I think it should be the other way around:
>    You want to send something without any fancy stuff? Use `send`.
>    You need more advanced outputs? Use `send_outputs`

We agree, we'll change it.

> 2. SendAmountParams:
>    a) Do we really need that as it's own object, class struct? Can't the send function be `send(amount, address, options)`?
>    b) If we keep it, can we rename the var to something else than `output` in the examples? It's confusing 😆 . Let's call it params or something

We don't really agree, there is more to `SendAmountParams` than just amount and address. Also these functions take an array of `SendAmountParams` and not a single amount/address tuple.

**Comment by Dr-Electron** [comment]
> We don't really agree, there is more to `SendAmountParams` than just amount and address. Also these functions take an array of `SendAmountParams` and not a single amount/address tuple.

But why can't the other options be part of "options"?
In most cases people probably just want to do something like `send(10, "rms...")` and for the 10% edge cases we provide something like `send(10, "rms...", Options::new().with_expiration())`

A function should always be optimised for the 90% of the use cases 🤔

**Comment by Alex6323** [comment]
Please have a look at #725 and comment on it whether you'ld be okay with it. I don't think merging the other params with the transaction options is a good idea, though.

**Comment by Thoralf-M** [comment]
Before closing this issue bindings still need to be updated with this https://github.com/iotaledger/iota-sdk/pull/725
