### ISSUE TITLE
Fix signEvm

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/iota-sdk#592]
## Description

PR to reproduce issue: https://github.com/iotaledger/iota-sdk/pull/591/files#diff-01878e48c3c3fa6cc4743c662d173b4530062f42652e0275d4411e00c55eabbb

At the moment, we are unable to use the sign EVM function for the Shimmer EVM. The main reason is twofold:
- We're lacking [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) compatibility.
- Tthe signature resolved from the v, r & s values resolves to different addresses if we try to get them using ethereum libraries.

## Motivation

It's important that the sdk provides ways to easily create transactions compatible with Shimmer EVM.

## Requirements

Write a list of what you want this feature to do.

1. Create signatures that are EIP-155 compatible
2. Sign Transactions
3. When we call the `getSenderAddress()` on a `Transaction` object, it should return the same address that `generateAddress` returns.

## Additional remarks

We added some remarks in the example PR that reproduces the issue described above:

- There is inconsistency between `generateEvmAddresses` & `signEvm` to pass in the correct address to sign with.
- Hardening keys shouldn't be done inside Typescript. Additionally, it should be hardened by default.
- The how to shows that `signEvm` is on secret manager but it is on the account?

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
Can I get the team's thoughts on this? Obviously when designing the API, I mimicked the design of `sign_ed25519`, which requires you to pass in a chain, but perhaps this can be improved?

> The how to shows that signEvm is on secret manager but it is on the account?

This is because the old bindings have no secret manager type. In the new bindings the method is on the secret manager.
