### ISSUE TITLE
Create NFT collection examples and add to docs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#597]
## Description

We should port the rust examples for nft collections and add them to the docs. Quite some people will be interested in that I guess.
Can your team @thibault-martinez help with the porting? Doesn't need to be perfect. I can than create the docs and unify or fix examples if needed

## Motivation

Many people are interested in L1 NFT collections

## Requirements

1. Port examples to nodejs and python
2. Create docs
3. Merge :trollface: 

## Are you planning to do it yourself in a pull request?

Yes and No :trollface:

**Comment by thibault-martinez** [comment]
We will do a PR and you can push the documentation stuff to it, fine by you?

**Comment by Dr-Electron** [comment]
Sounds good
