### ISSUE TITLE
Create most important client examples

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#599]
## Description

I think we forgot some important client examples for the docs. 
Stuff like get node info could be added. How to use the indexer API.
Maybe also mqtt? (Although that is not supported yet everywhere? 🤔)

## Are you planning to do it yourself in a pull request?

Yes I can definitively create some. But please provide input first ;)

**Comment by thibault-martinez** [comment]
You're only speaking about docs and bindings, right? Because these examples exist in Rust.

**Comment by Dr-Electron** [comment]
> You're only speaking about docs and bindings, right? Because these examples exist in Rust.

Yes

**Comment by thibault-martinez** [comment]
We are happy to add some examples but please do a list of what you would like.

**Comment by Dr-Electron** [comment]
It's fine, I will create those. Tbh I'm not sure yet what we need. 
So I will create examples for node info and indexer (if needed) and add them to the docs.

We can always add examples to the docs later if we get requests from the community 🤔
