### ISSUE TITLE
Update overview image

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#600]
## Description

I think we still need to update [this image](https://github.com/iotaledger/iota-sdk/blob/develop/documentation/sdk/static/img/iota_layers_overview.svg).
At least remove Java and Bee. But we also need to add wallet (btw I think this is the wrong image anyway 🤔 ) and so on

## Are you planning to do it yourself in a pull request?

Yes, I can do it. But first I need approval from the team on how the image should look like and what it should contain

**Comment by thibault-martinez** [comment]
Yeah it would be pretty identical I guess, remove Java, replace iota.rs with SDK and remove bee.

**Comment by thibault-martinez** [comment]
Please do it :)

**Comment by thibault-martinez** [comment]
Maybe put the bindings core between the SDK and the bindings, it's a separate crate (`iota-sdk-bindings-core`)

**Comment by Dr-Electron** [comment]
Will create a new image 👍
