### ISSUE TITLE
Unify "Build a Foundry Output" example

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#61]
## Description

The [Build a Foundry Output](https://wiki.iota.org/shimmer/iota.rs/how_tos/build_foundry_output/) examples explain different features in different languages.
This issue is part of the efforts in iotaledger/iota-sdk#59 

## Motivation

We should show/explain the same features in all languages (if they exist).

## Requirements

Let's show in every example how to:

- [ ] Remove the unneeded code of how to create an Alias output
    - [ ] Rust
    - [x] Nodejs
    - [x] Python
    - [x] Java 
- [ ] Explain how to melt token
    - [x] Rust
    - [ ] Nodejs
    - [ ] Python
    - [ ] Java 
- [ ] Explain how to send native token
    - [x] Rust
    - [ ] Nodejs
    - [ ] Python
    - [ ] Java 
- [ ] Remove content without foundry (See open question)
    - [x] Rust
    - [ ] Nodejs
    - [ ] Python
    - [ ] Java 

## Open questions (optional)

Not sure about the last point. It would be nice to have this guides in the bindings. I'm just not sure if it should be part of this how-to. Maybe we could create a Native Token section or something and split it up.

But If you want instead of removing it, you can also add it to the bindings so that we can split it up later more easily

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
Superseded by https://github.com/iotaledger/iota-sdk/issues/414
