### ISSUE TITLE
Non-trivially removable DTOs

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#622]
- [ ] MigratedFundsEntryDto
- [x] OutputMetadataDto
- [x] ProtocolParametersDto
- [ ] AccountDetailsDto
- [ ] TransactionDto
- [ ] OutputDataDto
- [ ] PreparedMintTokenTransactionDto
- [ ] MintTokenTransactionDto
- [ ] TransactionOptionsDto
- [ ] BlockDto
- [ ] InputSigningDataDto
- [ ] StrongholdDto
- [ ] BurnDto
- [ ] RemainderDataDto
- [ ] SignedTransactionDataDto
- [ ] PreparedTransactionDataDto
- [x] NetworkInfoDto

**Comment by DaughterOfMars** [comment]
I think everything has been examined and the only one left that I think could be removed is `FeatureDto`. Not sure if it's worth it.
