### ISSUE TITLE
lower permissions file with mnemonic on windows

### ISSUE THREAD

**Issue by qrayven** [iotaledger/iota-sdk#624]
## Description
Windows has a much different permission model than POSIX, (UNIX).
Files containing the mnemonic should have been saved by CLI with permissions similar to 600 on the UNIX system. 

https://github.com/iotaledger/iota-sdk/pull/611#discussion_r1231960169

## Motivation

Its a good security practice to use a layered security model

## Requirements

Write a list of what you want this feature to do.

1.  the ile containing a mnemonic shouldn't be read by other users or groups of users than the user that starts the process 

## Open questions (optional)

what is the secure equivalence of 0600 on Windows?

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1281
