### ISSUE TITLE
Ideas for client refactoring

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#63]
With the new changes, mainly the new ISA, we should check if we can change/remove the following things
- [x] Having both `ClientBlockBuilder` and `ClientBlockBuilderOptions` feels a bit weird
- [ ] Check if all DTOs are actually useful
- [x] Make `is_alias_transition()` public, so `alias_state_transition()` can be removed from wallet.rs?
- [x] Remove SecretManageExt?

**Comment by DaughterOfMars** [comment]
- [x] Evaluate `Into` impls for types which take references

**Comment by DaughterOfMars** [comment]
I think ClientBlockBuilder/Options are necessary.

**Comment by DaughterOfMars** [comment]
As annoying as it can be using `Into` with references, the alternatives are even worse. There are probably places where we could do better with memory management but at the end of the day I think the effects are pretty minimal.

**Comment by DaughterOfMars** [comment]
Given that there are now separate issues for DTO changes, I think it's fair to close this in favor of those.
