### ISSUE TITLE
Make sure all public interfaces are documented

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#634]
## Description

Currently if you look for something in our API references you will find classes and interfaces which are not properly documented. For example:
https://wiki.iota.org/next/iota-sdk/references/nodejs/interfaces/CreateAccountPayload/
https://github.com/iotaledger/iota-sdk/blob/3bccd150c8a1104a09221ebf2017add17c2c63f8/bindings/nodejs/lib/types/wallet/account.ts#L156-L160

Would be nice to see at least which properties this interface has

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
- [x] Python
- [x] Nodejs
