### ISSUE TITLE
Unify "Get a Block" example

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-sdk#64]
## Description

The [Get a Block](https://wiki.iota.org/shimmer/iota.rs/how_tos/get_block/) examples explain different features in different languages.
This issue is part of the efforts in iotaledger/iota-sdk#59 

## Motivation

We should show/explain the same features in all languages (if they exist).

## Requirements

Let's show in every example how to:

- [ ] Don't show again on how to create a block. We already know that. Instead do it the Rust way and use a random tip. (That way we even include new info on how to fetch tips :trollface: ) We could probably even get rid of the get id from env part in the rust example
    - [ ] Rust (Remove env part and just use a random tip)
    - [ ] Nodejs
    - [ ] Python
    - [ ] Java

- [ ] Explain how to get block metadata
    - [ ] Rust
    - [x] Nodejs
    - [x] Python
    - [ ] Java 

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
We have get block metadata in Rust already here https://github.com/iotaledger/iota-sdk/blob/develop/sdk/examples/client/node_api_core/08_get_block_metadata.rs
There it's one example for every core endpoints, so adding this to the other example would be weird
Do you want a new examples with both then?

**Comment by Dr-Electron** [comment]
I would say as long as everything is documented in at least one example it is fine. So you can skip that part. 
So you can remove it from the node.js and python example, but create new ones for the bindings if needed 🤔
