### ISSUE TITLE
[Bug]: Crash when creating `AccountManager`

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/iota-sdk#645]
### Issue description

In both the new sdk bindings and the old iota/wallet bindings, we dont seem to be able to work with the `AccountManager`
Issue explained in discord 
https://discord.com/channels/397872799483428865/1047518088536531137/1120736366955855922

### Version

`wallet-nodejs-binding-v2.0.3-rc.36` -> `wallet-nodejs-binding-v2.0.3-rc.39`

### Expected behaviour

-

### Actual behaviour

-

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
Should be fixed, please reopen if not the case.
