### ISSUE TITLE
Align Python serialization

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#650]
## Description

Currently in the wallet we have MyEncoder https://github.com/iotaledger/iota-sdk/blob/4c25849ff8cc472d561f4494bc4d2542f0c4dbfc/bindings/python/iota_sdk/wallet/common.py#L15 which converts the types to a dict, but in the client not https://github.com/iotaledger/iota-sdk/blob/4c25849ff8cc472d561f4494bc4d2542f0c4dbfc/bindings/python/iota_sdk/client/client.py#L142-L153, so in the client methods we make sure that the types are converted to dicts if required already before like here https://github.com/iotaledger/iota-sdk/blob/4c25849ff8cc472d561f4494bc4d2542f0c4dbfc/bindings/python/iota_sdk/client/client.py#L246-L257
For some types like the amount where we change the type from int to str it might be required, but to convert classes to dicts it shouldn't be necessary to do that manually.

## Motivation

Aligned/cleaner code

## Open questions (optional)

What's the best way to do it?

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
`dacite` seems to be good option at least for dataclasses as used here https://github.com/iotaledger/iota-sdk/pull/720/files

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1824
