### ISSUE TITLE
cli:  extended list of outputs

### ISSUE THREAD

**Issue by qrayven** [iotaledger/iota-sdk#654]
## Description

Currently, the list of outputs looks like this: 
```
Account "main": outputs
Outputs: [
    OutputId(0x6f86544527a9b76093db90c0ae1e50f1b58a78a9572f407aad6e2400e6008fe30600),
]
```
Which doesn't say a lot. 
It would be great to refactor the list that contains the relative number and type. i.e: 
```
0  0x000000 alias
1  0x111111 nft

```

## Motivation

Improve UX, give the user better information about associated outputs with the account

## Requirements

```
Account "main": outputs
0  0x000000 alias
1  0x111111 nft

```
## Open questions (optional)

should we have additional details in a row beside the type of output? 

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/955
