### ISSUE TITLE
cli: list-accounts command

### ISSUE THREAD

**Issue by qrayven** [iotaledger/iota-sdk#658]
## Description

Currently, when creating a new account (with optional alias) we are unable to list all created accounts associated with the wallet.
The `list-accounts` would be helpful to see accounts created in the past, about which users could simply forget. 

## Motivation

improved UX.  Users can see all created accounts with associated aliases

## Requirements

Write a list of what you want this feature to do.

1. new command `list-accounts` that would list accounts with aliases

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/950
