### ISSUE TITLE
cli: refer to transaction by index number

### ISSUE THREAD

**Issue by qrayven** [iotaledger/iota-sdk#659]
## Description

The list of transactions is printed in the following form:
```
Account "main": txs
0    0x00f18755ed603b63bbfc6c4d41668cd823ce28dff2fc15ddb77315006f69a9f9 2023-06-21 14:46:48
1    0x00f18755ed603b63bbfc6c4d41668cd823ce28dff2fc15ddb77315006f69a9f9 2023-06-21 14:46:48
```
It would be great to get the details of the transaction by providing only the index number instead of the whole id.
```
Account "main": tx 0
```

## Motivation

Improved UX, faster navigation through transactions

Explain why this feature is needed.

## Requirements

Write a list of what you want this feature to do.

1.  `tx  0`
2. `tx  0x00f18755ed603b63bbfc6c4d41668cd823ce28dff2fc15ddb77315006f69a9f9`
 
## Open questions (optional)

Decide if it's worth implementing because it could require the transaction should be always printed in the same order

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1033
