### ISSUE TITLE
cli:  addresses formatted as Bech32

### ISSUE THREAD

**Issue by qrayven** [iotaledger/iota-sdk#677]
## Description
when printing details of outputs, transactions etc the addresses are encoded in hex format. 
On the other end, when we use the `addresses` command, the addresses are printed in bech32 format.

This brings confusion, especially when we want to validate the address attached to the account. 

## Motivation

improves the UX and navigation.

## Requirements

Write a list of what you want this feature to do.

1. either print an additional hex repr of address when using the `addresses` subcommand or print bech32 repr of addresses when printing the details transactions, outputs, etc

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/960
