### ISSUE TITLE
Investigate: Nodejs bindings wrapper type

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#699]
Investigate if we can change the bindings wrappers into something more usable.
Currently its a type wrapped in a struct, that aint pretty

See #679

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/iota-sdk/pull/679#discussion_r1246655377

**Comment by Thoralf-M** [comment]
Not needed anymore/done in https://github.com/iotaledger/iota-sdk/pull/1578
