### ISSUE TITLE
Add ConflictReasons strings to python (and rust)

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#708]
## Description

https://github.com/iotaledger/iota-sdk/pull/639 added 2 files that we need to add to python and investigate how to do in rust:
- [bindings/nodejs/lib/types/models/conflict-reason.ts](https://github.com/iotaledger/iota-sdk/pull/639/files/57fbc09cf254aa3137d12ccd84d549a71948a05e#diff-5042ca1c916f2ed87dd6d38fd9f0af535d99c36e6d31104c36fbd9e954578d8e)

## Motivation

Feature parity

## Open questions (optional)

Do we actually want this?

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1069
