### ISSUE TITLE
Move MinimumRequiredStorageDeposit from AccountMethod to ClientMethod

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#716]
## Description

Move `MinimumRequiredStorageDeposit` from `AccountMethod` to `ClientMethod` since the Account isn't needed for it
Also update the bindings

**Comment by JanaganSaravanan** [comment]
Hi!, @Thoralf-M , I would like to work on this issue. Can you please give me more info such as file path and how can i update the bindings ? Thanks

**Comment by Thoralf-M** [comment]
Hey @JanaganSaravanan, nice to hear!
May look like a lot at first glance, but it's actually pretty simple:

On the Rust side the methods is defined in an enum here https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/core/src/method/account.rs#L123-L126
and needs to be moved to https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/core/src/method/client.rs

Then it gets called here https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/core/src/method_handler/account.rs#L106-L113
and this would need to be moved to https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/core/src/method_handler/client.rs#L71

This update then needs to be reflected in the nodejs and python bindings (bindings/nodejs, /bindings/python). If you use the [search](https://github.com/search?q=repo%3Aiotaledger%2Fiota-sdk%20MinimumRequiredStorageDeposit&type=code) you'll also see something in `‎sdk/src/wallet/message_interface/*` and `sdk/src/wallet/bindings/nodejs/*` these should *not* be updated since we don't have a client there and will remove it soon.

NodeJs:
https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/nodejs/lib/wallet/account.ts#L733-L749 needs to be moved to https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/nodejs/lib/client/client.ts#L59

https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/nodejs/lib/types/wallet/bridge/account.ts#L182 to https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/nodejs/lib/types/client/bridge/client.ts

Python:
https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/python/iota_sdk/wallet/account.py#L269-L276 to https://github.com/iotaledger/iota-sdk/blob/d2f179df926511d2f9a13f645f43e129c6d61a2d/bindings/python/iota_sdk/client/client.py#L27

Let me know if you have any further questions!

**Comment by Thoralf-M** [comment]
Hi @JanaganSaravanan, are you working on this? 
Just asking for our planning, we would like to have this ready by the end of next week
If you can't do it by then, we will do it ourselves

**Comment by JanaganSaravanan** [comment]
I am really sorry for the late reply. I caught up in some work So i could not focus on this issue. Please work on this issue. Again I am sorry for the inconvenience.

**Comment by Thoralf-M** [comment]
No worries, thanks for the response
