### ISSUE TITLE
[Bug]: `Utils.parseBech32Address` fails on valid address

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/iota-sdk#748]
### Issue description

The function `Utils.parseBech32Address` in sdk-wasm fails on a valid address with a JSON conversion error.

### Version

`@iota/sdk-wasm` at version `1.0.0-rc.0`

### Expected behaviour

Successfully returns the address.

### Actual behaviour

Fails with this error:

```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.parseBech32Address (/home/philipp/git/identity.rs/bindings/wasm/node_modules/@iota/sdk-wasm/out/lib/utils/utils.ts:174:16)
  ...
```

(Note that the line number in utils.ts might be off by a bit as I started to add some print statement for debugging).

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Call `const addr = Utils.parseBech32Address("tst1qp8vegfcnf4vjcn0zj6a5wv4x0x6pmrw543a02gr50cqmrdtjf9cycygj6l")`

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Also shouldn't expect Ed25519 here since it can also be alias/nft
https://github.com/iotaledger/iota-sdk/blob/0977f26a06e79086a5d01af9f1a5d8813dfdc07c/bindings/nodejs/lib/utils/utils.ts#L173

**Comment by DaughterOfMars** [comment]
I believe the problem is that we don't have a unifying class, just an abstract class for `Address`.

```rust
abstract class Address {
    private type: AddressType;

    constructor(type: AddressType) {
        this.type = type;
    }
    /**
     * The type of address.
     */
    getType(): AddressType {
        return this.type;
    }

    abstract toString(): string;
}
```

Currently the fn returns that `Address` superclass, so I figure we either need to read the json type first then deserialize as the concrete type or just create an actual `Address` with the type field.
