### ISSUE TITLE
Add setters for `Amount` and `FoundryCounter`

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/iota-sdk#756]
## Description

In the nodejs/Wasm bindings, there doesn't seem to be a way to set the `amount` on an existing `AliasOutput` instance. The same is true for the `foundryCounter` on an Alias.

## Motivation

When updating an existing chain output, like an Alias, it's useful to get the output from the node, update the fields that need to be changed, say state metadata, and then set the updated amount since the required storage deposit has changed. This also applies to NFT Outputs and might also apply to the other output types. It might be worthwhile to ensure all properties on outputs have setters as part of this

## Requirements

Write a list of what you want this feature to do.

For identity we need at least:

1. `setAmount` for `AliasOutput` and `NftOutput`.
2. `setFoundryCounter` for `AliasOutput`.

## Are you planning to do it yourself in a pull request?

No.

**Comment by thibault-martinez** [comment]
As discussed, we won't do that as it would break the syntactic validation rules. The way to go is to use the builder functions again. Feel free to open more issues if you want some convenience methods to make it easier.
