### ISSUE TITLE
Reorganize `Utils` functions

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/iota-sdk#760]
### Move util functions to concrete types

```
const nftAddress: Address = new NftAddress(Utils.nftIdToBech32(nftId, networkName));
```

Consider making the `nftIdToBech32` function internal to `NftAddress`, e.g.:

```
const nftAddress: Address = NftAddress.fromNftId(nftId, networkName));
```

- The same applies to
    - `Utils.aliasIdToBech32`.
    - `Utils.computeTokenId`. It already returns a `TokenId` so is just a constructor for `TokenId` without living on the type itself.
    - `Utils.computeOutputId`

### Conversion function from Output ID to UTXOInput

Add a constructor for `UTXOInput` that has the functionality of `TransactionHelper.inputFromOutputId` from iota.js.

### Move top-level functions to Utils namespace

The `utf8ToBytes`, `utf8ToHex` and `hexToUtf8` functions are directly in the top-level namespace of the sdk. Consider moving thos "util" functions to the `Utils` namespace.

### Nits

- `Utils.computeNftId` returns a `string` instead of the type alias `NftId`.

## Motivation

The address util functions take a `string` and return one and it's not immediately obvious what that string represents, especially for new users, I imagine. So having them directly on the stronger-typed classes like `AliasAddress` seems both clearer and more convenient.
Constructors should live on the classes that they construct rather than in `Utils`. A user checking the API docs for how to construct a certain type would check that type's docs and rarely consider that a constructor is in `Utils`.

The constructor `new UTXOInput` requires a transaction ID and output index, but it's not easily possible to extract those from some `outputID`, because that is just a string. There should be a convenient way to convert.

## Are you planning to do it yourself in a pull request?

No.

**Comment by abdulmth** [comment]
> const nftAddress: Address = new NftAddress(Utils.nftIdToBech32(nftId, networkName));

`NFTAddress`  takes an `NFTId` which is hex encoded string, there's no need to convert it to `Bech32`. Same for other address classes. 

> Utils.computeTokenId. It already returns a TokenId so is just a constructor for TokenId without living on the type itself

`TokenId` is a type alias for string, it doesn't have a constructor. 

> Add a constructor for UTXOInput that has the functionality of TransactionHelper.inputFromOutputId from iota.js.

Will be added.

> The utf8ToBytes, utf8ToHex and hexToUtf8 functions are directly in the top-level namespace of the sdk. Consider moving thos "util" functions to the Utils namespace

Everything is top level right now, since there isn't many util functions, keeping everything top level can be beneficial to avoid breaking changes if directory structure changes.

> Utils.computeNftId returns a string instead of the type alias NftId

Will be corrected.

**Comment by PhilippGackstatter** [comment]
> NFTAddress takes an NFTId which is hex encoded string, there's no need to convert it to Bech32. Same for other address classes.

True. Not high priorty, and can be changed non-breakingly, but the parameter name of the constructor of `AliasAddress` and `NftAddress` should take `aliasId: AliasId` and `nftId: NftId` respectively, not `address` as it currently does. That's where my confusion that the constructor needed a bech32 address initially came from.
