### ISSUE TITLE
Assign numeric strings a type instead of `string` in node.js

### ISSUE THREAD

**Issue by abdulmth** [iotaledger/iota-sdk#796]
## Description

Some values, e.g. the amount of base tokens, are serialized as a decimal numeric string. Using a type, for example: 
```typescript 
declare type NumericString = string;
```
 to annotate them would improve readability.

Probably, this change will affect the external API in a non-breaking way.

## Motivation

Confusion between hex encoded strings and numeric strings.

## Are you planning to do it yourself in a pull request?
Maybe

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1340
