### ISSUE TITLE
Fix coverage CI

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#80]

**Comment by Thoralf-M** [comment]
Currently runs out of space https://github.com/iotaledger/iota-sdk/actions/runs/4543898340/jobs/8009202692

**Comment by thibault-martinez** [comment]
@rajivshah3 Do you have ideas on how to deal with `= note: /usr/bin/ld: final link failed: No space left on device` ?

**Comment by rajivshah3** [comment]
That's bizarre, I'm surprised it's taking up so much space. I'll take a look and see what might be going on

**Comment by rajivshah3** [comment]
@thibault-martinez I think it may be building the CLI, SDK, and all of the SDK bindings. Is this intended or did you just want to collect coverage info about the CLI and SDK crate?

**Comment by Thoralf-M** [comment]
We're only interested in the SDK crate
