### ISSUE TITLE
[Bug]: Update NewOutputWalletEvent class properties signature

### ISSUE THREAD

**Issue by brancoder** [iotaledger/iota-sdk#818]
### Issue description

Update `NewOutputWalletEvent` class properties signature to
```
output: OutputData;
transaction?: ITransactionPayload;
transactionInputs?: IOutputResponse[]
```

### Version

Relevant for "old" nodejs bindings release candidate 40 (v2.0.3-rc.40)

### Expected behaviour

transactionInputs?: IOutputResponse[]

### Actual behaviour

denotes an array of one:
transactionInputs?: [IOutputResponse]

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/822
