### ISSUE TITLE
[Bug]: `Utils.computeStorageDeposit` fails with serialization error

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/iota-sdk#856]
### Issue description

`Utils.computeStorageDeposit` fails with an internal serialization error. It seems due to defining a `rentStructure` key in TS but the required key being `rent`:

https://github.com/iotaledger/iota-sdk/blob/04d4868365149815360b0823b3e01c2495699741/bindings/nodejs/lib/types/utils/bridge/utils.ts#L68

https://github.com/iotaledger/iota-sdk/blob/04d4868365149815360b0823b3e01c2495699741/bindings/core/src/method/utils.rs#L137

### Version

```
"@iota/sdk-wasm": "^1.0.0-rc.1"
```

### Expected behaviour

Returns the computed storage deposit.

### Actual behaviour

Fails with an error.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Call `Utils.computeStorageDeposit` on a valid output.

### Errors

```
Example error: missing field `rent` at line 1 column 1548
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/858
