### ISSUE TITLE
Add new parents field to Block - rust

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#883]
https://github.com/iotaledger/tips-draft/blob/tip46/tips/TIP-0046/tip-0046.md#basic-block

**Comment by Thoralf-M** [comment]
This is done by https://github.com/iotaledger/iota-sdk/commit/15df0acab307406fe2891c077e06393c7e0d79b3 already?

**Comment by thibault-martinez** [comment]
> This is done by [15df0ac](https://github.com/iotaledger/iota-sdk/commit/15df0acab307406fe2891c077e06393c7e0d79b3) already?

No, I added the new parents type but didn't add the 3 fields to Block, just transformed the existing one

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/925
