### ISSUE TITLE
[Bug]: Rust crate does not compile with `client` and `tls` features only

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/iota-sdk#897]
### Issue description

`iota-sdk` does not compile with `client` and `tls` feature. Adding the `"wallet"` feature is a "fix".

### Version

Rust crate, 1.0.0

### Expected behaviour

Reproduction example succeeds without errors.

### Actual behaviour

Reproduction example fails.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. `cargo new --lib test && cd test`
2. `cargo add iota-sdk@1.0.0 --no-default-features --features client,tls`
3. `cargo check`

### Errors

```
    Checking iota-sdk v1.0.0
error[E0433]: failed to resolve: could not find `wallet` in the crate root
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iota-sdk-1.0.0/src/client/node_manager/syncing.rs:132:82
    |
132 |     pub async fn update_node_manager(&self, node_manager: NodeManager) -> crate::wallet::Result<()> {
    |                                                                                  ^^^^^^ could not find `wallet` in the crate root

error[E0282]: type annotations needed
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iota-sdk-1.0.0/src/client/node_manager/syncing.rs:154:9
    |
154 |         Ok(())
    |         ^^ cannot infer type of the type parameter `E` declared on the enum `Result`
    |
help: consider specifying the generic arguments
    |
154 |         Ok::<(), E>(())
    |           +++++++++

Some errors have detailed explanations: E0282, E0433.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `iota-sdk` (lib) due to 2 previous errors
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by thibault-martinez** [comment]
@PhilippGackstatter Thanks for the report, can you see if https://github.com/iotaledger/iota-sdk/pull/898 fixes it please?

**Comment by PhilippGackstatter** [comment]
@thibault-martinez Works on my end, thanks!

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/898
