### ISSUE TITLE
Add ContextInput - python

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#911]
Blocked by https://github.com/iotaledger/iota-sdk/issues/902, https://github.com/iotaledger/iota-sdk/issues/904 and https://github.com/iotaledger/iota-sdk/issues/907

https://github.com/iotaledger/tips-draft/blob/tip45/tips/TIP-0045/tip-0045.md#context-inputs

**Comment by Thoralf-M** [comment]
Started in https://github.com/iotaledger/iota-sdk/pull/1193, if the PRs for the other types update it, then this issue should also be done

**Comment by kwek20** [comment]
Thanks!

**Comment by kwek20** [comment]
@thibault-martinez i think we consider this done right? ContextInput is added

**Comment by thibault-martinez** [comment]
> @thibault-martinez i think we consider this done right? ContextInput is added

Not until the PR is merged, no
