### ISSUE TITLE
Add ContextInput - nodejs

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#912]
Blocked by https://github.com/iotaledger/iota-sdk/issues/903, https://github.com/iotaledger/iota-sdk/issues/905 and https://github.com/iotaledger/iota-sdk/issues/908

https://github.com/iotaledger/tips-draft/blob/tip45/tips/TIP-0045/tip-0045.md#context-inputs

**Comment by abdulmth** [comment]
done in #999
