### ISSUE TITLE
Adapt fields of RegularTransactionEssence - python

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#917]
Blocked by https://github.com/iotaledger/iota-sdk/issues/911 and https://github.com/iotaledger/iota-sdk/issues/915

https://github.com/iotaledger/tips-draft/blob/tip45/tips/TIP-0045/tip-0045.md#serialized-layout

**Comment by abdulmth** [comment]
blocked by https://github.com/iotaledger/iota-sdk/issues/915 and https://github.com/iotaledger/iota-sdk/issues/911

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1201
