### ISSUE TITLE
Add CI step for most common combinations of features

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#919]
Find out about the most common combinations of features used by other projects (e.g. identiity) and add a CI step to check it compiles.

https://github.com/iotaledger/iota-sdk/issues/897

**Comment by Thoralf-M** [comment]
stronghold without storage is one such combination I think

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1254
