### ISSUE TITLE
CI: Auto-format on merge

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iota-sdk#920]
CI Failing because you forgot to do a yarn lint?
Quickly updating a file on the fly without your code editor?

No problem! Github auto format on merge to the rescue!
No more waiting time for format, less github runners means more money!

TODO: 
- [ ] GH Action for `cargo fmt`
- [ ] GH Action for `yarn lint`
- [ ] GH Action for python `yapf`

Pros:
- Automation for everyone

Cons:
- Possible code injection when formatter gets hijacked

**Comment by thibault-martinez** [comment]
My 2 cents, I think we should all take 10mins to automate this on our local setup and then I don't see why it would be required in the CI.
Conceptually, I do not feel comfortable with the idea of merging unseen and unapproved code, sounds like unnecessarily opening ourselves to potential security risks.

**Comment by DaughterOfMars** [comment]
I think the benefits outweigh the risks here, and I don't think formatting alone should hold back a PR.

**Comment by thibault-martinez** [comment]
The team voted in favour of local formatting only.
