### ISSUE TITLE
Remove promote and change reattach to reissuePayload

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#934]
## Description

Remove promote and change reattach to reissuePayload

## Motivation

Promoting blocks doesn't really make sense anymore since the confirmation rate is expected to be good and it costs mana to do this. Rename of reattach, because only the Payload can be sent in a new block, the old block can't be sent again

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thibault-martinez** [comment]
I kinda started this in https://github.com/iotaledger/iota-sdk/pull/700 but not sure about the state of it. Probably good to do it independently anyway.

**Comment by Thoralf-M** [comment]
Ah nice, happy to get your PR done first and then we can check what's left to do
