### ISSUE TITLE
TODOs for Node.js bindings v.2.0 

### ISSUE THREAD

**Issue by abdulmth** [iotaledger/iota-sdk#966]
1.  Consistent visibility for variables in TS classes https://github.com/iotaledger/iota-sdk/pull/961#discussion_r1277420849.

**Comment by Tuditi** [comment]
2. Remove getters on TS classes in favour of readonly properties

**Comment by kwek20** [comment]
3. update bigint type to the u64 type alias

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1218
